{ @Reference
@Tag { vanleunen1992 }
@Type { Book }
@Author { Mary-Claire van Leunen }
@Title { A Handbook for Scholars }
@Publisher { Oxford }
@Edition { Revised Edition }
@Year { 1992 }
}

{ @Reference
@Tag { shalit1996 }
@Type { Book }
@Author { Andrew Shalit }
@Title { Dylan Reference Manual }
@Publisher { Addison-Wesley }
@Edition { First Edition }
@Year { 1996 }
@Label { Sha96 }
}

{ @Reference
@Tag { dujardin1996 }
@Type { TechReport }
@Author { Eric Dujardin }
@Number { 2892 }
@Title { Efficient dispatch of multimethods in constant time with dispatch trees }
@Publisher { INRIA }
@Year { 1996 }
@Label { Du96 }
}
