<?php
require "shared.inc";
standard_header("What is Dylan?");
?>

<P>Peter Hinely wrote one of the more concise descriptions of Dylan:</P>

<BLOCKQUOTE>
<EM>Dylan is an advanced, object-oriented, dynamic language which supports
the rapid development of programs.  When needed, the programmer can later
optimize [his or her] programs for more efficient execution by supplying
type information to the compiler.  Nearly all entities in Dylan (including
functions, classes, and basic data types such as integers) are first class
objects. Additionally Dylan supports multiple inheritance, polymorphism,
multiple dispatch, keyword arguments, object introspection, and many other
advanced features...</EM>
</BLOCKQUOTE>

<P>Dylan is fast, flexible and capable of unusually sophisticated
abstractions. Some of its more interesting features include:</P>

<UL>
<LI><STRONG>An advanced object model.</STRONG> Dylan's object model is more
powerful than those of most maintstream languages, but more familiar than
what you'd find in an academic language.
<LI><STRONG>Efficiency <EM>and</EM> flexibility.</STRONG>
Dylan can be used as a dynamic prototyping language (like SmallTalk)
or an efficient compiled language. Functional Developer, Functional
Objects' Dylan compiler, generates code as good as that of most C
compilers.  Still, it provides an interactive prototyping environment
like those found in SmallTalk or Tcl/Tk.
<LI><STRONG>Support for advanced IDEs.</STRONG> The original implementation
of Dylan stored code in a database and provided multiple views of how
definitions were related. Cross-referencing, hypercode and online
documentation were all popular research topics among the language's
designers.
<LI><STRONG>Infix syntax.</STRONG> (Most languages, including C, are
infix. LISP is prefix and Forth is postfix.)
</UL>

<P>[ <A HREF="fragments.phtml">Code examples</A> |
<A HREF="goals.phtml">Our goals</A> ]</P>

<H3>The Downside of Dylan</H3>

<P>Dylan isn't without some serious shortcomings. It's not widely supported
as of the northern summer of 2001, with only two major implementations, one of
which (ours) is still incomplete. Several features of the language could be
more elegant, and there's a wickedly intricate set of tradeoffs when
implementing shared libraries.</P>

<P>[ <A HREF="downloading.phtml">Downloading Software</A> |
<A HREF="http://www.fun-o.com">Dylan for Windows</A> ]</P>

<?php standard_footer(); ?>
