<?php
require "shared.inc";
standard_header("About Gwydion Dylan");
?>

Gwydion Dylan is the Dylan compiler <A
HREF="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">originally</A>
created by a team at Carnegie Mellon University and now being maintained and
improved by Team Dylan under modern versions of Linux, FreeBSD, OSX, cygwin, and more.

Our <A HREF="downloading.phtml">current release</A> is a technology preview,
suitable for learning the Dylan programming language and building command-line
applications. Our long-term vision is to create one of the most advanced
software development tools available.</P>

<A HREF="/about-gwydion.phtml">&rsaquo; Who was Gwydion?</A>

<?php standard_footer(); ?>
