<?php
require "shared.inc";
standard_header("Where does this strange name come from?");
?>

<p>
<a href="http://www.cyberphile.co.uk/~taff/taffnet/mabinogion/gwydion.html">Gwydion</a>
is a character from the <a href="http://www.cyberphile.co.uk/~taff/taffnet/mabinogion/mabinogion.htm">Mabinogion</a>, a Welsh tale almost a thousand years old.
<p>
Gwydion is a powerful sorceror and master of illusion. He delights in trickery and is thought to have originated April Fools' Day when he conjured the armies to trick Aranrhod into arming Lleu. He is a lover of poetry and the art of the bards, and is the druid of the gods. He is persistent in his ventures and learns from experience. He is both subtle and devious, yet open and honest in his dealings with others. He takes responsibility in his actions and in the actions of his people.
<p>
And he's the father of Dylan in that story.

<?php standard_footer(); ?>
