<?php
require "shared.inc";
standard_header("Code Browser/IDE");
?>

<P>The Apple Dylan technology release contained a really great development
environment. You could build custom code browsing windows to look at your
code in various ways, drag and drop functions between source files, and
edit a running program. Some of the more powerful Java environments are
patterned after it, but none of them have implemented all the features
yet.</P>

<P><STRONG>[<A HREF="images/browsers1.png">Apple Dylan Screenshot #1</A>]
 [<A HREF="images/browsers2.png">Apple Dylan Screenshot #2</A>]</STRONG></P> 

<P><A HREF="gui.phtml">Gtk+ and Gnome</A> finally support enough widgets to recreate Apple's code
browser. Implementing the other features of Apple Dylan would probably
prove challenging, but they could be added to a code browser slowly over
time.</P>

<P>Ideally, our IDE would support a CORBA interface to outside tools. This
would allow programmers to use Emacs (or vi) but still get many of the
benefits of an integrated environment. Of course, Gwydion Dylan would
always be available from the command-line, too.</P>

<P>Does anyone have screenshots of advanced development environments?</P>

<?php standard_footer(); ?>
