<?php
require "shared.inc";
standard_header("Community Resources");
?>

<p>Here's how Dylan hackers keep up with what's going on...</p>

<dl>

<dt><strong><a href="news:comp.lang.dylan">comp.lang.dylan</a></strong></dt>

<dd><p>This is the newsgroup dedicated to the discussion of Dylan.  If you have
a question about the Dylan language or about something that will be of interest
to the Dylan community at large this is the preferred place for it.  It is one
of the few ways that the world at large can see that there is activity in the
Dylan community and thus aids us in our quest for World Domination.</p></dd>

<dt><strong>The #dylan IRC channel</strong></dt>
<dd>
<p>
The <a href="http://www.ircbrowse.com/cdates.html?channel=dylan">#dylan</a> channel
is where most of the day-to-day Dylan Q&amp;A takes place.  Since Dylan hackers are spread
around the world (New Zealand, Germany, East and West coast USA, South America,
...) there's usually someone online at all times of day.
</p>
<p>You can join the channel or browse and search the #dylan channel log:
</p>
<ul>
<li>
  <a href="irc://irc.freenode.net:6667/#dylan">Join the #dylan</a>
  channel via an <a href="http://en.wikipedia.org/wiki/IRC_client">IRC client</a>
 (see <a href="http://en.wikipedia.org/wiki/List_of_IRC_clients">IRC client list</a>).
</li>
<li>
  <a href="http://www.ircbrowse.com/cdates.html?channel=dylan">Browse the #dylan channel logs by dates</a> via irc.browse.com
</li>
<li>
   <a href="http://www.ircbrowse.com/register.html">Register at www.ircbrowse.com</a>
   for a free account and you can <a href="http://www.ircbrowse.com/search.html">search in the #dylan channel logs</a>
</li>
</ul>
<p>
To discuss coding issues you can paste your code to the #dylan channel via
<a href="http://paste.lisp.org">http://paste.lisp.org</a>, which provides these features:
<ul>
  <li>
    <a href="http://paste.lisp.org/new/dylan">Create a new paste to the #dylan channel</a>.
    Therefore you first enter the username, which you use on the #dylan channel. Then you type in a title,
    which describes the issue. Try to find a very specific one, that will improve the quality of browsing feature, which is desribed in the next item.
    And finally you paste a code snippet into the last field. That's it.
    The paste will be announced on the #dylan channel on Freenode.
  </li>
  <li>
    <a href="http://paste.lisp.org/list/dylan">Browse the pastes to the #dylan channel</a>.
  </li>
</ul>
</p>
<p>
Several agents communicate to the #dylan channel. For example, the #dylan channel reports
<ul>
  <li> Commits to the dylan repository </li>
  <li> New bug reports </li>
  <li> Pastes on paste.lisp.org </li>
</ul>
</p>
</dd>
<dt>
<strong>Dylan Mailing Lists</strong>
</dt>
<dd><p>Several Dylan mailing lists are listed below.  They can also be browsed at
<a href="http://blog.gmane.org/index.php?prefix=gmane.comp.lang.dylan.gwydion">gmane.comp.lang.dylan.gwydion</a>.</p>
</dd>
<dl>
<dt>
<strong><a href="/mailman/listinfo/gd-hackers">gd-hackers</a></strong>
<a href="mailto:gd-hackers-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="/pipermail/gd-hackers/">archives</a>
</dt>
<dd><p>Our public development list. Here's where we talk about improving
Gwydion Dylan and co-ordinate most of our development work. (A very small bit
happens behind the scenes.) If you want to contribute, this is the place to
start. Just post a message explaining what you'd like to do, and see what other
developers suggest. You can post small patches to the list, or upload big ones
to our FTP site. Lurkers are also welcome!</p>

<p>This list is moderated. The archived list is browsable at
<a href="http://blog.gmane.org/gmane.comp.lang.dylan.gwydion.devel">gmane.comp.lang.dylan.gwydion.devel</a>.</p></dd>

<dt>
<strong><a href="/mailman/listinfo/gd-announce">gd-announce</a></strong>
<a href="mailto:gd-announce-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="/pipermail/gd-announce/">archives</a>
</dt>

<dd><p>Find out about new Gwydion Dylan releases! This is an extremely
low-traffic list reserved for announcements. (If you subscribe to gd-hackers
below, you don't need to subscribe to this list.) The archived list is browsable at
<a href="http://blog.gmane.org/gmane.comp.lang.dylan.gwydion.announce">gmane.comp.lang.dylan.gwydion.announce</a>.</p></dd>

<dt>
<strong><a href="/mailman/listinfo/gd-chatter">gd-chatter</a></strong>
<a href="mailto:gd-chatter-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="/pipermail/gd-chatter/">archives</a>
</dt>

<dd><p>This list contains nothing but Subversion and Bugzilla output.  This is
for developers who need to know everything that's going on.
The archived list is browsable at
<a href="http://blog.gmane.org/gmane.comp.lang.dylan.gwydion.cvs">gmane.comp.lang.dylan.gwydion.cvs</a>.</p></dd>

</dl>
</dl>


<?php standard_footer(); ?>
