<?php
require "shared.inc";
standard_header("Community Resources");
?>

<p>Here's how Dylan hackers keep up with what's going on...</p>

<dl>

<dt><strong><a href="news:comp.lang.dylan">comp.lang.dylan</a></strong></dt>

<dd><p>This is the newsgroup dedicated to the discussion of Dylan.  If you have
a question about the Dylan language or about something that will be of interest
to the Dylan community at large this is the preferred place for it.  It is one
of the few ways that the world at large can see that there is activity in the
Dylan community and thus aids us in our quest for World Domination.</p></dd>

<dt><strong>The #dylan IRC channel</strong></dt>

<dd><p><a href="irc://irc.freenode.net:6667/#dylan">#dylan</a> is where most of
the day-to-day Dylan Q&amp;A takes place.  Since Dylan hackers are spread
around the world (New Zealand, Germany, East and West coast USA, South America,
...) there's usually someone online at all times of day.  Subversion commits
and new bug reports are also displayed (briefly) in the channel.</dd>

<dt>
<strong><a href="https://www.gwydiondylan.org/mailman/listinfo/gd-hackers">gd-hackers</a></strong>
<a href="mailto:gd-hackers-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="/pipermail/gd-hackers/">archives</a>
</dt>

<dd><p>Our public development list. Here's where we talk about improving
Gwydion Dylan and co-ordinate most of our development work. (A very small bit
happens behind the scenes.) If you want to contribute, this is the place to
start. Just post a message explaining what you'd like to do, and see what other
developers suggest. You can post small patches to the list, or upload big ones
to our FTP site. Lurkers are also welcome, too!</p>

<p>This list is moderated.</p></dd>

<dt>
<strong><a href="https://www.gwydiondylan.org/mailman/listinfo/gd-announce">gd-announce</a></strong>
<a href="mailto:gd-announce-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="/pipermail/gd-announce/">archives</a>
</dt>

<dd><p>Find out about new Gwydion Dylan releases! This is an extremely
low-traffic list reserved for announcements. (If you subscribe to gd-hackers
below, you don't need to subscribe to this list, too.)</p></dd>

<dt>
<strong><a href="https://www.gwydiondylan.org/mailman/listinfo/gd-chatter">gd-chatter</a></strong>
<a href="mailto:gd-chatter-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="/pipermail/gd-chatter/">archives</a>
</dt>

<dd><p>This list contains nothing but Subversion and Bugzilla output.  This is
for developers who need to know everything that's going on.</p></dd>

</dl>


<?php standard_footer(); ?>
