<?php
require "shared.inc";
standard_header("How Does Dylan Stack Up?");
?>

<P>When faced with the daunting task of learning a new programming language, it is reasonable to ask "What's in it for me?"  Why learn Dylan, rather than focus on brushing up those Java or .NET skills?  Well, as they say "The proof is in the pudding." (does anyone still say that?) -- or at least in the contest results.</P>

<P>The following information relates to Dylan's performance in the last few years of International Conference on Functional Programming (ICFP) Contest.  Contrary to the title, all kinds of languages are used for these projects (ranging from Java and C all the way down to Bash scripts!).</P>

<P>The following table summarizes Dylan's performance, with each statistic linking to a more detailed analysis of the work done.</P>

<P><STRONG>ICFP Performance</STRONG></P>
<TABLE cellspacing="10">
<TR>
  <TH>Year</TH><TH>Topic</TH><TH>Rank</TH>
</TR>
<TR>
  <TD><a href="http://www.dtek.chalmers.se/groups/icfpcontest">2003</a></TD><TD><a href="http://www.dtek.chalmers.se/groups/icfpcontest/task.html">Race track path algorithm</a></TD><TD>Stay Tuned!</TD>
</TR>
<TR>
  <TD><a href="http://icfpcontest.cse.ogi.edu">2002</a></TD><TD><a href="http://icfpcontest.cse.ogi.edu/task.html">Multi-Player Robert Game</a></TD><TD>Eliminated in Round 4</TD>
</TR>
<TR>
  <TD><a href="http://cristal.inria.fr/ICFP2001/prog-contest">2001</a></TD><TD><a href="http://cristal.inria.fr/ICFP2001/prog-contest/task.html">SML/NG Markup Language Optimizer</a></TD><TD><a href="http://www.gwydiondylan.org/icfp/icfp2001.html">Second Place</a></TD>
</TR>
<TR>
  <TD><a href="http://www.cs.cornell.edu/icfp/">2000</a></TD><TD><a href="http://www.cs.cornell.edu/icfp/task.htm">Ray Tracer</a></TD><TD>Eliminated First Round</TD>
</TR>
</TABLE>

<?php standard_footer(); ?>
