<?php
require "shared.inc";
standard_header("Dylan Hackers Conference");
?>

<pre>
                       
                          Invitation to

                     Dylan Hackers Conference

                     July, 26th - 28th, 2002
                               or
                     August, 2nd - 4th, 2002

                         Berlin, Germany


Dear Dylan friend!

The Dylan Hackers invite you to their first real life meeting,
happening this summer, hosted by the Chaos Computer Club in Berlin,
Germany.

The following topics are planned for discussion on this event:

 - Release of Gwydion Dylan 2.4
 - Future directions of Gwydion Dylan
 - Common Dylan and the Dylan language standard
 - Dylan 2.0?
 - Dylan and its Lisp heritage, including demonstration of Symbolics
   Lisp machine

Registration

  Please register as soon as possible by sending mail to
  dhc@berlin.ccc.de.  Please specify your travel and accomodation
  preferences, as outlined in the sections below.

Locations

  The conference itself will take place at the Chaos Computer Club
  Berlin (CCCB, http://berlin.ccc.de).  The address is:

    Marienstr. 11
    10117 Berlin

  or about here:

http://www.stadtplandienst.de/query?ORT=b;PLZ=10117;STR=Marienstr%2E;HNR=11;GR=2

  On Friday evening, we will meet at the c-base
  (http://www.c-base.de).  The c-base is an old
  space station that was discovered beneath the city of Berlin.  Address:

    Rungestr. 20
    10179 Berlin

  which is here:

http://www.stadtplandienst.de/query?ORT=b;PLZ=10179;STR=Rungestr%2E;HNR=20;GR=2

Travel

  The conference itself will take place on saturday and sunday.
  Suggested arrival is on thursday or friday, depending on where
  you're coming from and whether you want to spend some time
  sightseeing.  Early departure could be sunday evening, regular
  departure is on monday.

  If you do not want to plan your travel yourself, please contact the
  organizer.  We want to try to get a good deal on the flights.  In
  any case, inform us of your plans, so we can arrange travel from the
  airport to your hotel.

Accomodation

  We'll probably have three types of accomodation:

    - for free on some random hacker's couch
    - cheap hotel rooms (50EUR single, 70EUR double per night)
      likely at http://www.kuenstlerheim-luise.de/
    - mid-class hotel rooms (about 100EUR single, 150EUR double)
      likely at  http://www.hotel-albrechtshof.de/

  Both hotels are within a few hundred meters of the conference place,
  right in the heart of Berlin.

  Please let us know as soon as possible which type you prefer,
  whether you're traveling alone or in company, and how many nights
  you will want to stay.

Costs

  We're still looking for sponsorship for this event, so if your
  employer or university or dad has some money to spend, here's a good
  cause :).  Any money collected will be handed first to the persons
  who need it most: students, unemployed people, etc., so if lack of
  funds prevents you from coming, let us know and we look into it. If
  we can gather enough money, everybody will be reimbursed, of course.

  You'll need to calculate about EUR30 per day for food, plus cost
  of accomodation (depends on your preferences) and travel (depends on
  where you're coming from).

Preliminary schedule:

  Thursday, July 25th:
	Early Bird's Arrival (for compensating jet lag)

  Friday, July 26th:
        Official arrival

	12h: Sightseeing Berlin
	18h: Dylan Hackers Fireside Chat @ c-base

  Saturday, July, 27th:
        First conference day

	9h:      Breakfast @ CCCB
	10h-13h: Conference
	13h-14h: Lunch
	14h-18h: Conference
	18h-20h: Private Break @ Hotel
	20h-:    Fancy Dinner, Berlin Night life

  Sunday, July 28th:
        Second conference day

	9h:      Breakfast @ CCCB
	10h-13h: Conference
	13h-14h: Lunch
	14h-17h: Conference
	17h-18h: Private Break @ Hotel
        18h-:    Dinner and socializing @ CCCB

  Monday, July 29th:
        Departure

Organizer:

  All the paperwork will be handled by the Chaos Computer Club
  Veranstaltungs-GmbH.  We're able to write proper bills,
  official-looking invitations, and all the other stuff.  Your
  contact is Tim Pritlove, he's reading dhc@berlin.ccc.de.
</pre>



<?php standard_footer(); ?>
