<?php
require "shared.inc";
standard_header("Dylan Hackers Conference");
?>

<pre>
2nd International Dylan Hackers Conference (DHC 2004)


3 - 6 February, 2004


School of Mathematical and Computing Sciences
Victoria University of Wellington
Wellington, New Zealand.


-----------------------------------------------------------------------


Dear Dylan friend!


Dylan Hackers would like to invite you to attend the second international
conference to be held in the first week of February in the Computer Science
department of Victoria University, Wellington, New Zealand.


The conference is going to be held in the seminar room CO249 and a computer
lab CO244 adjacent to it. There are plans to host five seminar sessions on
the Dylan language presented by a range of New Zealand, German, and USA
based developers. The rest of the time will be spend discussing the roadmap
of the Dylan development and implementing a substantial part of the
compiler, as well as generally having a good time.


LOCATION and Opening Meeting:


The main two locations are rooms CO249 and CO244 (Cotton Building, Gate 7).
If you are having trouble locating the conference on site, please enquire at
the School of Mathematical and Computing Science office on the third floor -
they will have the immediate contact details of the conference organisers.


The Opening Meeting is to be held at 11 a.m. in CO249 on Tuesday, 3rd of
February. Everyone is welcome to attend, although an early registration of
interest expressed by email to alex@mcs.vuw.ac.nz would allow us to change
the room to a bigger one if necessary.


The plan for the rest of the conference is going to be maintained on the
Gwydion Dylan project web site (http://www.gwydiondylan.org/) and is subject
to change as the conference progresses. Although the times for the seminars
are going to stay fixed.


ACCOMMODATION and TRAVEL:

If you need help arranging the accommodation and travel, please contact Alex
Potanin on alex@mcs.vuw.ac.nz, otherwise Wellington City Council maintains
an excellent web site with convenient travel information here:
http://www.wellingtonnz.com/accommodation/ . Any hotel downtown of
Wellington, for example Ibis, will be within 15 minute walk or a cable car
ride from the venue.


PRELIMINARY SCHEDULE:


Monday, 2nd of February:

Early bird arrival. Compensating jet lag for our international visitors at
Paraparaumu airport.


Tuesday, 3rd of February:

First conference day

11:00 a.m. - Opening Meeting (CO249)

1:00 p.m.  - Lunch

2:00 p.m.  - "Introducing Dylan" Seminar (CO249)

4:00 p.m.  - First day programming session followed by dinner (CO244)


Wednesday, 4th of February:

Second conference day

9:00 a.m.  - Second day programming session (CO244)

10:30 a.m. - Morning tea (CO339)

11:00 a.m. - "Rapid Prototyping in Dylan and ICFP" Seminar (CO249)

1:00 p.m.  - Lunch

2:00 p.m.  - "Dylan in	 Operating Systems" Seminar (CO249)

3:00 p.m.  - "What is going on in programming sessions" Session (CO249)

3:30 p.m.  - Afternoon tea (CO339)

4:00 p.m.  - Second day programming session (CO244)


Thursday, 5th of February:

Third conference day

9:00 a.m.  - Third day programming session (CO244)

10:30 a.m. - Morning tea (CO339)

11:00 a.m. - "Post-facto Type Inference and Advanced Dylan" Seminar (CO249)

1:00 p.m.  - SMCS Seminar on Agile Methods (CO249)

2:00 p.m.  - Lunch with ELVIS (CO339)

3:00 p.m.  - Third day programming session (CO244)


Friday, 6th of February:

Fourth conference day (Waitangi Day)

9:00 a.m.  - Fourth (and final) day programming session (CO244)

10:30 a.m. - Morning tea (CO339)

11:00 a.m. - "Dylan in Secure Operating Systems Design" Seminar (CO249)

1:00 p.m.  - Lunch

2:00 p.m.  - Fourth day programming session (The Final Hack) (CO244)

4:00 p.m.  - "DHC 2004 Final Report and Presentation" Seminar (CO249)


NB! The dinners will be organised on each individual night by those involved
in the programming sessions. If you want to take part in each night's
dinner, you are encouraged to participate or attend the programming
sessions. :-) But you are welcome to talk to the conference organisers on
the day if you still want to attend the dinner and skip the programming
session.


For more information please contact:

Alex Potanin
PhD Student
SMCS, VUW

<a href="mailto:alex@mcs.vuw.ac.nz">alex@mcs.vuw.ac.nz</a>

<a href="http://www.mcs.vuw.ac.nz/~alex/">http://www.mcs.vuw.ac.nz/~alex/</a>
</pre>


<?php standard_footer(); ?>
