<?php
require "shared.inc";
standard_header("Documentation");
?>

<P>Unfortunately, Dylan has a pretty steep learning curve for people used
to C and C++. (Java experience helps quite a bit, though.) Dylan's not
particularly hard, but several of the concepts require "unlearning" various
ways of designing object-oriented programs.</P>

<?php
begin_progress_table();
progress("Gwydion Introduction", 4);
progress("Dylan for Advanced C++ Programmers", 9);
progress("Gwydion Reference cleanup", 4);
end_progress_table();
?>

<P>We'll put more documentation online as people express interest and we
clean it up.</P>

<?php standard_footer(); ?>
