<?php
require "shared.inc";
standard_header("Documentation");
?>

<P>This documentation is still under heavy development. Many sections still
need to be written; others are written but have yet to be converted to
DocBook format. You can find older documentation on the FTP site.</P>

<P>Peter Housel has been instrumental in converting this documentation to
DocBook-XML format.</P>

<p>All DocBook-XML-based documents are available in two forms: all on one
HTML file, or one HTML page per section.</p>

<p>See also <a href="learning.phtml">learning Dylan</a>, your
<strong>first stop</strong> when you're new to the
language. Tutorials, introductions, articles.</p>


<h3>General Dylan Docs</h3>

<DL>

<DT><STRONG><A HREF="books/drm/">Dylan Reference Manual</A></STRONG>
 (<A href="books/drm/drm_errata.html">Errata</A>)

<DD><P>The official definition of the Dylan language and standard library.</P>

</DL>

<h3>Gwydion Dylan Docs</h3>

<DL>

<DT><STRONG><A HREF="gdref/gduser.html">Gwydion Dylan User's
Manual</A></STRONG> (<a href="gdref/gduser/">split version</a>)

<DD><P>The user's guide for Gwydion. This <STRONG>includes a brief
tutorial</STRONG> on creating and compiling Dylan programs, plus a
reference for the d2c compiler and other tools. (Written mostly by Gwydion
Group at CMU.)</P>

<DT><STRONG><A HREF="gdref/gdmaint.html">Gwydion Dylan Maintainer's Manual</A></STRONG>
(<a href="gdref/gdmaint/">split version</a>)

<DD><P>Reference material describing the internals of various tools. Quite
helpful if you're working on d2c or Mindy. (Written mostly by Gwydion Group
at CMU.)</P>

<DT><STRONG><A HREF="gdref/gdapi.html">d2c API
documentation</A></STRONG> (<a href="gdref/gdapi/">split version</a>)

<DD><P>Reference material describing the internals of d2c, the Gwydion
Dylan compiler.  (Written by Neel Krishnaswami.)</P>

<DT><STRONG><A HREF="gdref/gdlibs.html">Gwydion Dylan Library Reference</A></STRONG>
(<a href="gdref/gdlibs/gdlibs.html">split version</a>)

<DD><P>Documentation for the various libraries included with Gwydion
Dylan. (Written mostly by Gwydion Group at CMU.)</P>

<DT><STRONG><A HREF="gdref/gdcore/html/index.html">Updated Gwydion Dylan Core Library Reference</A></STRONG>

<DD><P>Updated and complete reference documentation for most of the libraries included with Gwydion Dylan. A work in progress.</P>

</DL>


<h3>Open Dylan Docs</h3>

These docs still refer to "Functional Developer", which was the name
of Open Dylan before it became open source.

<dl>
<dt>
<strong><a HREF="documentation/opendylan/env/index.htm">Getting Started with Functional Developer</a></strong>
<dd><p>Describes Open Dylan's interactive development environment.</p>

<dt>
<strong><a HREF="documentation/opendylan/dguide/index.htm">Building Applications Using
DUIM</a></strong>
<dd><p>Describes how to use DUIM (Dylan User Interface Manager),
the portable window programming toolkit.</p>

<dt>
<strong><a HREF="documentation/opendylan/core/index.htm">Common Dylan and Functional Extensions library reference</a></strong>

<dd><p>Describes the Open Dylan implementation of the Dylan language, a common
set of Dylan libraries, and a library interchange mechanism. The common libraries
provide many language extensions, a threads interface, and object finalization.</p>

<dt>
<strong><a HREF="documentation/opendylan/io/index.htm">System and I/O library reference</a></strong>
<dd><p>Describes Open Dylan's printing and output formatting modules,
a streams module, a sockets module, and modules providing an interface to operating system features such as the file system, time and date information, and the host machine environment.</p>

<dt>
<strong><a HREF="documentation/opendylan/dref/index.htm">DUIM library reference</a></strong>
<dd><p>Describes the libraries forming DUIM (Dylan User Interface Manager),
the portable window programming toolkit. It complements
Building Applications Using DUIM.</p>

<dt>
<strong><a HREF="documentation/opendylan/interop1/index.htm">C FFI and Win32 library
reference</a></strong>
<dd><p>Describes a foreign function interface library for interoperation
with C programs, and several libraries providing a low-level interface
to the Microsoft Win32 API.</p>

<dt>
<strong><a HREF="documentation/opendylan/interop2/index.htm">OLE, COM, ActiveX and DBMS library reference</a></strong>
<dd><p>Describes high and low level interfaces to COM,
OLE, and ActiveX component technology, and generic DBMS support, through
SQL with an ODBC backend.</p>

<dt>
<strong><a HREF="documentation/opendylan/corba/index.htm">Developing Component Software with CORBA</a></strong>
<dd><p>A tutorial and reference for CORBA interoperability using the Functional Developer ORB.</p>

</dl>

<H3>Older Manuals</H3>

<P>This is the documentation for Gwydion Dylan 2.0. We have translated
all the old manuals to DylanDoc (a variant of Docbook), so the above
links should be complete and more up-to-date. For historical reasons,
and in case we've missed a detail in the translation, here are the
original documents.</P>

<DL>

<DT><STRONG><A HREF="old-docs/maker-out/httoc.htm">Gwydion Dylan 2.0 Reference</A></STRONG>
<DD><P>Covers Mindy and the standard libraries in great detail.</P>

<DT><STRONG><A HREF="old-docs/htdocs/index.html">Gwydion Dylan 2.0 Documentation Index</A></STRONG>
<DD><P>The original documentation index from CMU's web site. Note that many
of these links are broken.</P>

</DL>

<P>[ <A HREF="learning.phtml">Learning Dylan</A> ]</P>

<?php standard_footer(); ?>

