<?php
require "shared.inc";
standard_header("Downloading Software");
?>

<P><EM>Gwydion Dylan <?php current_version();?></EM> is the current release
version of Gwydion Dylan. It is a development release, not finished software.
Be sure to review the <A
HREF="limitations.phtml">limitations</A>.</P>

<H3>Dependencies</H3>

<p>Gwydion Dylan uses a number of other tools which you will need to obtain
if your system doesn't already have them.  Mindy compiler and interpreter
binaries are stand-alone, but to use d2c to develop Dylan programs you will of
course require a C compiler, linker, make and so forth.  Most platforms also
require GNU libtool, and we supply some utility scripts that use Perl.

<p>If you want to build your own d2c from source then you will also need GNU
autoconf, automake and m4.

<p>Using the d2c compiler to build compiled Dylan programs requires the
<a href="http://www.hpl.hp.com/personal/Hans_Boehm/gc">Boehm-Demers-Weiser
conservative garbage collector</a>.  Gwydion versions 2.3.9 and
earlier come with the GC library included but with 2.3.10 and later we have
decided for a number of reasons that it is better for the user (or OS
vendor) to supply the GC library.


<H3>Available Packages></H3>

<P>To use the d2c compiler, you'll normally want to download precompiled
binaries for your platform (d2c is written in Dylan). Binary tarballs are
available for several different platforms, and the following RPMs are
available:</P>

<UL>
<LI><STRONG>gwydion-dylan:</STRONG> Binaries for the d2c compiler and the
Melange interface generator. Most of the documentation is in this package.
<LI><STRONG>gwydion-dylan-extras:</STRONG> Various utilities which
generally aren't required to use Gwydion Dylan. Skip these unless you need
something specific.
<LI><STRONG>mindy:</STRONG> The Mindy Dylan interpreter. A very small
download, but it doesn't contain much documentation. You can find
everything that's missing on this web site.
</UL>

<H3>Download Sites</H3>

<UL>
<LI><A HREF="downloads/">Gwydion Dylan HTTP server</A>
<LI><A HREF="ftp://ftp.gwydiondylan.org/pub/gd/">Gwydion Dylan FTP Server</A>
<LI><A HREF="ftp://berlin.ccc.de/pub/gd/">Chaos Computer Club</A>, Germany
<LI><A HREF="ftp://ftp.fu-berlin.de/pub/unix/languages/dylan/">FU Berlin</A>, Germany (no packages, just source)
<LI><A HREF="ftp://ftp.ntua.gr/pub/lang/gwydion">National Technical University of Athens</a>, Greece
<LI><A HREF="ftp://gd.tuwien.ac.at/languages/gwydiondylan/">Vienna University of Technology</a>, Austria
<LI><A HREF="ftp://dylan.fortunaty.net/software/gd/">fortunaty.net</a>, Germany
</UL>

<H3>CVS Source Repository</H3>

<P><A HREF="http://www.gwydiondylan.org/cgi-bin/viewcvs.cgi">Browse our CVS
tree.</A> You can also access the cvs server directly, specify
<tt>:pserver:anoncvs@cvs.gwydiondylan.org:/var/lib/cvs</tt> as your
CVS root. The password is <tt>anoncvs</tt>. Even though we haven't yet
released a newer official "stable" release we think we've made
<strong>great</strong> progress and improvements since then and
generally recommend people to start from the most recent tagged
version which is currently <?php current_version();?>.  If that works
for you (or you're the type that doesn't read manuals before turning
on your new VCR) then you can try the HEAD version.  We actually try
pretty hard to make sure the HEAD version always works but there are
certainly even fewer guarantees with it than usual :-)</P>

<H3>Debian</H3>

Gwydion Dylan is part of the standard distribution of woody and
sid. Just type <tt>apt-get install gwydion-dylan-dev</tt>.

<H3>Fink</H3>

Gwydion Dylan is part of the
<A HREF="http://fink.sf.net/">Fink distribution</A>
for Darwin and MacOS X.
Just type <tt>apt-get install gwydion-dylan</tt>.

<H3>FreeBSD</H3>

Gwydion Dylan is available as the <tt>lang/dylan</tt> port in FreeBSD.

<?php standard_footer(); ?>
