<?php
require "shared.inc";
standard_header("Downloading Software");
?>

<P><EM>Gwydion Dylan <?php current_version();?></EM> is the current release
version of Gwydion Dylan. It is a development release, not finished software.
Be sure to review the <A
HREF="limitations.phtml">limitations</A>.</P>

<P>To use the d2c compiler, you'll normally want to download precompiled
binaries for your platform (d2c is written in Dylan). Binary tarballs are
available for several different platforms, and the following RPMs are
available:</P>

<UL>
<LI><STRONG>gwydion-dylan:</STRONG> Binaries for the d2c compiler and the
Melange interface generator. Most of the documentation is in this package.
<LI><STRONG>gwydion-dylan-extras:</STRONG> Various utilities which
generally aren't required to use Gwydion Dylan. Skip these unless you need
something specific.
<LI><STRONG>mindy:</STRONG> The Mindy Dylan interpreter. A very small
download, but it doesn't contain much documentation. You can find
everything that's missing on this web site.
</UL>

<H3>Download Sites</H3>

<P>Because Gwydion Dylan is a large package, please try to select a mirror
near you. (If you'd like to provide a mirror, write to <A
HREF="mailto:andreas@andreas.org">Andreas Bogk</A>.)</P>

<UL>
<LI><A HREF="ftp://berlin.ccc.de/pub/gd/">Chaos Computer Club</A>, Germany
<LI><A HREF="ftp://ftp.fu-berlin.de/pub/unix/languages/dylan/">FU Berlin</A>, Germany (no packages, just source)
<LI><A HREF="ftp://ftp.ntua.gr/pub/lang/gwydion">National Technical University of Athens</a>, Greece
<LI><A HREF="ftp://gd.tuwien.ac.at/languages/gwydiondylan/">Vienna University of Technology</a>, Austria
</UL>

<H3>CVS Source Repository</H3>

<P><A HREF="http://berlin.ccc.de/cgi-bin/cvsweb/gd/">Browse our CVS tree.</A>
You can also access the cvs server directly, specify
<tt>:pserver:anoncvs@berlin.ccc.de:/home/cvsroot</tt> as your CVS root. The
password is <tt>anoncvs</tt>. The very conservative can find version 2.2 on
the branch GD_2_2_STABLE, but even though we haven't yet released a newer
official "stable" release we think we've made <strong>great</strong> progress
and improvements since then and generally recommend people to start from the
most recent tagged version which is currently <?php current_version();?>.
If that works for you (or you're the type that doesn't read manuals before
turning on your new VCR) then you can try the HEAD version.  We actually try
pretty hard to make sure the HEAD version always works but there are certainly
even fewer guarantees with it than usual :-)</P>

<?php standard_footer(); ?>
