<?php
require "shared.inc";
standard_header("Documentation");
?>

<P>This documentation is still under heavy development. Many sections still
need to be written; others are written but have yet to be converted to
DocBook format. You can find older documentation on the FTP site.</P>

<P>Peter Housel has been instrumental in converting this documentation to
SGML format. However, our DSSSL stylesheets still need some debugging, and
occasionally omit various forms of credit (such as chapter authors). To
ensure that credit is given where credit is due, the descriptions below
include authorship information.</P>

<p>All SGML-based documents are available in two forms: all on one
HTML file, or one HTML page per section.</p>

<DL>

<DT><STRONG><A HREF="gdref/gduser.html">Gwydion Dylan User's
Manual</A></STRONG> (<a href="gdref/gduser/gduser.html">split version</a>)
<DD><P>The user's guide for Gwydion. This <STRONG>includes a brief
tutorial</STRONG> on creating and compiling Dylan programs, plus a
reference for the d2c compiler and other tools. (Written mostly by Gwydion
Group at CMU.)</P>

<DT><STRONG><A HREF="learning.phtml">Learning Dylan</A></STRONG>
<DD><P>Your <strong>first stop</strong> when you're new to the language. Tutorials, introductions, articles.</P>

<DT><STRONG><A HREF="books/drm/drm_1.html">Dylan Reference Manual</A></STRONG>
[<A HREF="http://www.fun-o.com/products/books.phtml#drm">paper, US$41.95</A>] (<A href="books/drm/drm_errata.html">Errata</A>)

<DD><P>The official Dylan language standard, including a reference to
all the built-in functions and classes. (This used to be hosted at
Harlequin, but it's gone. I've put up a local copy, and hope that the
copyright holders don't mind. Go out and buy the printed version of
this document to support their fine work!)</P>

<DT><STRONG><A HREF="gdref/gdlibs.html">Gwydion Dylan Library Reference</A></STRONG>
(<a href="gdref/gdlibs/gdlibs.html">split version</a>)
<DD><P>Documentation for the various libraries included with Gwydion
Dylan. (Written mostly by Gwydion Group at CMU.)</P>

<DT><STRONG><A HREF="http://www.fun-o.com/products/doc/index.phtml">Functional Objects Documentation</A></STRONG>
<DD><P>We'd like to be as compatible to Functional Developer as
possible. We either implement compatible APIs, such as Common Dylan
and C-FFI, or use the libraries provided by Functional Objects under
an Open Source license (thanks guys!). You can find their documenation
online there.</P>

<DT><STRONG><A HREF="gdref/gdmaint.html">Gwydion Dylan Maintainer's Manual</A></STRONG>
(<a href="gdref/gdmaint/gdmaint.html">split version</a>)
<DD><P>Reference material describing the internals of various tools. Quite
helpful if you're working on d2c or Mindy. (Written mostly by Gwydion Group
at CMU.)</P>

<DT><STRONG><A HREF="gdref/gdapi.html">d2c API documentation</A></STRONG>
(<a href="gdref/gdapi/book1.html">split version</a>)
<DD><P>Reference material describing the internals of d2c. 
(Written by Neel Krishnaswami.)</P>

</DL>

<H3>Older Manuals</H3>

<P>This is the documentation for Gwydion Dylan 2.0. We have translated
all the old manuals to DylanDoc (a variant of Docbook), so the above
links should be complete and more up-to-date. For historical reasons,
and in case we've missed a detail in the translation, here are the
original documents.</P>

<DL>

<DT><STRONG><A HREF="old-docs/maker-out/httoc.htm">Gwydion Dylan 2.0 Reference</A></STRONG>
<DD><P>Covers Mindy and the standard libraries in great detail.</P>

<DT><STRONG><A HREF="old-docs/htdocs/index.html">Gwydion Dylan 2.0 Documentation Index</A></STRONG>
<DD><P>The original documentation index from CMU's web site. Note that many
of these links are broken.</P>

</DL>

<P>[ <A HREF="learning.phtml">Learning Dylan</A> ]</P>

<?php standard_footer(); ?>
