<?php
require "shared.inc";
standard_header("Documentation");
?>

<P>This documentation is still under heavy development. Many sections still
need to be written; others are written but have yet to be converted to
DocBook format. You can find older documentation on the FTP site.</P>

<P>Peter Housel has been instrumental in converting this documentation to
SGML format. However, our DSSSL stylesheets still need some debugging, and
occasionally omit various forms of credit (such as chapter authors). To
ensure that credit is given where credit is due, the descriptions below
include authorship information.</P>

<DL>

<DT><STRONG><A HREF="gdref/gduser/book1.htm">Gwydion Dylan User's Manual</A></STRONG>
<DD><P>The user's guide for Gwydion. This includes a brief tutorial on
creating and compiling Dylan programs, plus a reference for the d2c
compiler and other tools. (Written mostly by Gwydion Group at CMU.)</P>

<DT><STRONG><A HREF="http://www.harlequin.com/products/ads/dylan/doc/drm/">Dylan Reference Manual</A></STRONG>
<DD><P>The official Dylan language standard, including a reference to all the built-in functions and classes. (This is provided coutesy of Harlequin, Ltd., and is hosted on their website. Thanks!)</P>

<DT><STRONG><A HREF="gdref/gdlibs/book1.htm">Gwydion Dylan Library Reference</A></STRONG>
<DD><P>Documentation for the various libraries included with Gwydion
Dylan. (Written mostly by Gwydion Group at CMU.)</P>

<DT><STRONG><A HREF="gdref/gdmaint/book1.htm">Gwydion Dylan Maintainer's Manual</A></STRONG>
<DD><P>Reference material describing the internals of various tools. Quite
helpful if you're working on d2c or Mindy. (Written mostly by Gwydion Group
at CMU.)</P>

<DT><STRONG><A HREF="gdref/tutorial/book1.htm">Advanced Dylan Tutorial</A></STRONG>
<DD><P>A tutorial on many aspects of Dylan programming, with special
coverage of topics likely to be confusing to C and C++
programmers. (Written by Eric Kidd.)</P>

</DL>

<?php standard_footer(); ?>
