<?php
require "shared.inc";
standard_header("Overview");
?>

<P>We're a group of volunteers working to create new development tools,
with a focus on Unix-like systems. We have updated <A
HREF="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">CMU's
Gwydion Dylan</A>, fixing many bugs and making it work well under modern
versions of Linux and FreeBSD. Our <A HREF="downloading.phtml">current
release</A> is a technology preview, suitable for learning Dylan and
building modest command-line applications. In the future, we want to create
one of the most advanced development tools available and donate it to the
<A HREF="http://www.gnu.org/">GNU project</A>.</P>

<P>Please feel free to join us! You can look at <A HREF="goals.phtml">our
goals</A>, some <A HREF="fragments.phtml">code examples</A>, or one of the
following resources:</P>

<P>[
<A HREF="about-dylan.phtml">What is Dylan?</A> |
<A HREF="learning.phtml">Learning Dylan</A> |
<A HREF="http://www.harlequin.com/devtools/dylan">Dylan for Windows</A>
]<BR>[
<A HREF="limitations.phtml">Limitations</A> |
<A HREF="downloading.phtml">Downloading</A> |
<A HREF="gdref.phtml">Documentation</A> |
<A HREF="lists.phtml">Mailing Lists</A> ]</P>

<H3>Recent News</H3>

<DL>

<DT><STRONG>OpenBSD/Sparc Port, xformat library (29 Apr
1999)</STRONG></DT> <DD><P>Brad Dominy has ported Gwydion Dylan to
OpenBSD. Version 2.2.0 can be found on the usual<A
HREF="downloading.phtml">mirror</A> sites in the contributions
directory. Future versions such as the upcoming 2.3.1 development
version will of course include the patches.</P> Also in the
contributions directory is David Lichteblaus port of the Common Lisp
format library to Dylan, which is way more powerful than the native
format library.

<DT><STRONG>PCRE interface library 0.1 released (6 Apr 1999)</STRONG></DT>
<DD><P>The initial version of the PCRE (Perl Compatible Regular Expressions)
interface is available from the contributions directory of any of our
<A HREF="downloading.phtml">mirror</A> sites. This version provides a
one-to-one mapping from the native PCRE C API into Dylan. The next release
will extend this greatly.</P>

<DT><STRONG>Mac version of mindy available (1 Apr 1999)</STRONG></DT>

<DD><P>Due to the efforts of Rob Myers, mindy, the Dylan interpreter
from the Gwydion Dylan package, is available for the Macintosh. You
can get it from usual location, the contributions directory of any of
our <A HREF="downloading.phtml">mirror</A> sites.</P>

<DT><STRONG>MySQL interface library 0.1 released (11 Mar 1999)</STRONG></DT>

<DD><P>The MySQL interface is still work in progress, but all the
low-level stuff is there, and it has been used successfully together
with the cgi-lib. You can download it from the contrib directory of any
<A HREF="downloading.phtml">mirror</A> site.</P>

<DT><STRONG>Peter Hinely's CGI Library Updated (12 Feb 1999)</STRONG></DT>

<DD><P>Peter Hinely has released a new version of his CGI library. You can
download it from the contrib directory of any <A
HREF="downloading.phtml">mirror</A> site.</P>

<DT><STRONG>Gwydion Dylan 2.2.0 Released (7 Feb 1999)</STRONG></DT>

<DD><P>We've been busy talking with Harlequin about language
standardization, but 2.2.0 is finally ready! You can download it from any
of our <A HREF="downloading.phtml">mirrors</A>. See the <A
HREF="release-2.2.phtml">official announcement</A> for more
information.</P>

<P>This represents over nine months of work and the labors of many
volunteers. Thank you to everyone who helped out!</P>

</DL>

<P>[ <A HREF="news.phtml">Older News</A> |
<A HREF="lists.phtml">Mailing List Archives</A> ]</P>

<?php standard_footer(); ?>
