<?php
require "shared.inc";
standard_header("Overview");
?>

<BLOCKQUOTE>

<EM>Dylan is an advanced, object-oriented, dynamic language which supports
rapid program development.  When needed, programs can be optimized for more
efficient execution by supplying more type information to the compiler.  Nearly
all entities in Dylan (including functions, classes, and basic data types such
as integers) are first class objects. Additionally Dylan supports multiple
inheritance, polymorphism, multiple dispatch, keyword arguments, object
introspection, macros, and many other advanced features...  --Peter Hinely</EM>

</BLOCKQUOTE>

<p>For more on the background and goals of the Dylan language, see the <a
href="/books/drm/drm_6.html">Introduction to the Dylan Reference Manual</a>.
To get a quick feel of the language have a look at some <a
href="fragments.phtml">code examples</a>.</p>

<p>For an overview over the available implementations of Dylan, see <a href="implementations">here</a>.</p>

<p>Please feel free to join us!  You can look at <a
href="projects.phtml">projects that need work</a> and <a
href="community.phtml">community resources</a>.</p>

<br>
<br>
<h2>Recent News</h2>

<DL>
<?php

$db = db_connect();

$query = "select * from news where time >= subdate(now(), interval 1 year) order by time desc";
$res = mysql_query($query, $db);
$err = mysql_error();
if($err) {
    echo "MySQL error occurred. Please notify <a href=andreas@andreas.org>Andreas</a>.";
} else {
    while($row = mysql_fetch_row($res)) {
        echo "<DT><STRONG>".$row[1]." (".$row[0].")</STRONG></dt>\n";
        echo "<DD><P>".$row[2]."\n\n";
   }
}
?>
</DL>

<P>[ <A HREF="news.phtml">Older News</A> |
<A HREF="community.phtml">Mailing List Archives</A> ]</P>

<?php standard_footer(); ?>
