<?php
require "shared.inc";
standard_header("Overview");
?>

<P>We're a group of volunteers working to create new development tools,
with a focus on Unix-like systems. We have updated <A
HREF="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">CMU's
Gwydion Dylan</A>, fixing many bugs and making it work well under modern
versions of Linux and FreeBSD. Our <A HREF="downloading.phtml">current
release</A> is a technology preview, suitable for learning Dylan and
building modest command-line applications. In the future, we want to create
one of the most advanced development tools available and donate it to the
<A HREF="http://www.gnu.org/">GNU project</A>.</P>

<P>Please feel free to join us! You can look at <A HREF="goals.phtml">our
goals</A>, some <A HREF="fragments.phtml">code examples</A>, or one of the
following resources:</P>

<P>[
<A HREF="about-dylan.phtml">What is Dylan?</A> |
<A HREF="learning.phtml">Learning Dylan</A> |
<A HREF="http://www.harlequin.com/devtools/dylan">Dylan for Windows</A>
]<BR>[
<A HREF="limitations.phtml">Limitations</A> |
<A HREF="downloading.phtml">Downloading</A> |
<A HREF="gdref.phtml">Documentation</A> |
<A HREF="lists.phtml">Mailing Lists</A> ]</P>

<H3>Recent News</H3>

<DL>

<DT><STRONG>Code Freeze for Gwydion Dylan 2.2 (24 Dec 1998)</STRONG></DT>

<DD><P>We've frozen the code in CVS in anticipation of our forthcoming 2.2
release. Look for a final test version, and then the real thing!</P>

<DT><STRONG>Gwydion Dylan Status Report (24 Dec 1998)</STRONG></DT>

<DD>
<P>We're pushing towards a code freeze now. A few outstanding bugs need
fixing (see the <STRONG>critical</STRONG> section in the bug tracker), bits
of Melange need further study, and our documentation is still not
completely resolved.</P>

<P>Jeff Dubrule has ported Mindy to run on a 64-bit system (RedHat 5.2
Alpha), and has started work on d2c. (These ports will not be included
in 2.2.) Peter Housel and Matthias Hoelzl have been stomping bugs left and
right, and Eric Kidd has rewritten getopt and cooked up some man pages.
Andreas has been working to make Melange play nicely with Gtk+, and Peter
Hinely has been helping edit our documentation. Shaleh has bootstrapped d2c
under Debian, and should have debs sometime soon.</P>
</DD>

</DL>

<P>[ <A HREF="news.phtml">Older News</A> |
<A HREF="lists.phtml">Mailing List Archives</A> ]</P>

<?php standard_footer(); ?>
