<?php
require "shared.inc";
standard_header("Learning Dylan");
?>

<p>Dylan differs from most mainstream languages in several subtle
ways. If you're really immersed in how one particular language works,
you'll have to let go of some of your knowledge. Dylan's generic
functions and access control, for example, are probably unfamiliar.
You'll have to learn these all over again, but will be rewarded with
more flexibility when you do.</p>

<p>We recommend using the Open Dylan &quot;Interactor&quot; when you
first start learning Dylan since it provides instant feedback. (The
Interactor is analogous to a Lisp Listener or a Python REPL.) Open
Dylan also allows downloading code into running applications, which
can be extremely useful when learning the language and making many
rapid modifications.</p>

<p>The following references might be good places to start:</p>

<dl>
<dt><strong><a href="fragments.phtml">12 Dylan Fragments</a></strong>

<dd><p>Twelve standalone code fragments show off the
features of the Dylan programming language (well, eight of them currently). If you want to get a feel for
things, this might be a good place to start.</p>

<dt><strong><a href="books/dpg/">Dylan Programming: An Object-Oriented and Dynamic Language</a></strong>

<dd><p>A good Dylan tutorial by several Harlequin employees.</p>

<dt><strong><a href="http://devworld.apple.com/dev/techsupport/develop/issue21/21strassman.html">A First Look at Dylan: Classes, Functions, and Modules</a></strong>

<dd><p>Steve Strassmann wrote a brief article on Dylan for
<cite>develop</cite>. It covers classes, functions and modules, and
provides good examples.</p>

<dt><strong><a href="gdref/tutorial.html">Advanced Dylan Tutorial</a></strong>
(<a href="gdref/tutorial/">split version</a>)

<dd><p>A quick and dirty introduction to Dylan for reasonably skilled
programmers. It covers the diffences between Dylan and other popular
programming languages. Some of the later chapters are unfinished, and the
examples feel contrived.</p>

<dt><strong><a href="books/drm/">The Dylan Reference Manual</a></strong>

<dd><p>The official Dylan reference, available online or as a
well-bound softcover book. If you're the type who likes to go right
to the language reference to learn, then by all means go here first,
but most people seem to agree this isn't the easiest way to learn
Dylan. If you already know a smattering of Dylan, and can only get
one book, this is your best bet.</p>

<dt><strong><a href="http://www.norvig.com/ltd/doc/ltd.html">Converting Common Lisp to Dylan</a></strong>

<dd><p>A set of notes on the pitfalls of translating a Common Lisp program
into Dylan. Should be of interest to people wishing to migrate Allegroserv
or other CL applications.</p>
</dl>


<p>[ <a href="gdref.phtml">Documentation</a> ]</p>


<?php standard_footer(); ?>
