<?php
require "shared.inc";
standard_header("Learning Dylan");
?>

<P>Dylan looks a bit like C or Pascal, and includes lots of funky features
which are hidden deep inside Perl and Python. If you're familiar with any
of these languages (and you have done some object-oriented programming)
you'll be to get started with Dylan quickly.</P>

<P>Dylan <EM>does</EM> differ from most maintstream languages in several
subtle ways. If you're really immersed in how one particular language
works, you'll have to let go of some of your knowledge. (Dylan's member
functions and access control, for example, are probably unfamiliar. You'll
have to learn these all over again, but will be rewarded with more
flexibility when you do.)</P>

<P>The following references might be good places to start:</P>

<DL>
<DT><STRONG>12 Dylan Fragments</STRONG>

<DD><P><EM>Coming soon.</EM> Twelve standalone code fragments show off the
features of the Dylan programming language. If you want to get a feel for
things, this might be a good place to start.</P>

<DT><STRONG>Dylan Programming</STRONG> [<A HREF="http://www.harlequin.com/products/ads/dylan/editions.shtml#dylprog">paper, US$30.95</A>]

<DD><P>A good Dylan tutorial by several Harlequin employees. This
goes into much more detail than any of the online resources, but some of
the examples feel a little bit contrived. If you want to order an
introductory book, <EM>Dylan Programming</EM> is your best bet.</P>

<DT><STRONG><A HREF="http://localhost/~emk/gdwww/gdref/tutorial/book1.htm"</A>Advanced Dylan Tutorial</A></STRONG> [<A HREF="http://www.pobox.com/~emk/dylan/">alternate formatting</A>]

<DD><P>A quick and dirty introduction to Dylan for reasonably skilled
programmers. It covers the diffences between Dylan and other popular
programming languages. Some of the later chapters are unfinished, and the
examples feel contrived.</P>

<DT><STRONG><A HREF="http://www.harlequin.com/products/ads/dylan/doc/drm/">The Dylan Reference Manual</A></STRONG> [<A HREF="http://www.harlequin.com/products/ads/dylan/editions.shtml#refman">paper, US$41.95</A>]

<DD><P>The official Dylan reference, available online or as a well-bound
softcover book. Harlequin has graciously made this available on their web
site. You won't be able to learn Dylan from this, but you can certainly
fill out your knowledge of the details. If you already know a smattering of
Dylan, and can only get one book, this is your best bet.</P>


</DL>

<P>[ <A HREF="gdref.phtml">Documentation</A> ]</P>


<?php standard_footer(); ?>
