<?php
require "shared.inc";
standard_header("Learning Dylan");
?>

<P>Dylan looks a bit like C or Pascal, and includes lots of funky features
which are hidden deep inside Perl and Python. If you're familiar with any
of these languages (and you have done some object-oriented programming)
you'll be to get started with Dylan quickly.</P>

<P>Dylan <EM>does</EM> differ from most maintstream languages in several
subtle ways. If you're really immersed in how one particular language
works, you'll have to let go of some of your knowledge. (Dylan's member
functions and access control, for example, are probably unfamiliar. You'll
have to learn these all over again, but will be rewarded with more
flexibility when you do.)</P>

<P>The following references might be good places to start:</P>

<DL>
<DT><STRONG><A HREF="fragments.phtml">12 Dylan Fragments</A></STRONG>

<DD><P>Twelve standalone code fragments show off the
features of the Dylan programming language. If you want to get a feel for
things, this might be a good place to start.</P>

<DT><STRONG><A HREF="http://www.gwydiondylan.org/books/dpg/db_1.html">Dylan Programming</A></STRONG> [<A HREF="http://www.fun-o.com/products/books.phtml#dp">paper, US$30.95</A>]

<DD><P>A good Dylan tutorial by several Harlequin employees. This
goes into much more detail than any of the online resources. The known issue with the book is that statements like if and case are not explained until chapter 11.5, whereas they were probably better introduced around chapter 5. But that's just a minor inconvenience. If you want to order an
introductory book, <EM>Dylan Programming</EM> is your best bet.</P>

<DT><STRONG><A HREF="http://devworld.apple.com/dev/techsupport/develop/issue21/21strassman.html">A First Look at Dylan: Classes, Functions, and Modules</A></STRONG>

<DD><P>Steve Strassmann wrote a brief article on Dylan for
<CITE>develop</CITE>. It covers classes, functions and modules, and
provides good examples.</P>

<DT><STRONG><A HREF="gdref/tutorial.html">Advanced Dylan Tutorial</A></STRONG>
(<a href="gdref/tutorial/tutorial.html">split version</a>)

<DD><P>A quick and dirty introduction to Dylan for reasonably skilled
programmers. It covers the diffences between Dylan and other popular
programming languages. Some of the later chapters are unfinished, and the
examples feel contrived.</P>

<DT><STRONG><A HREF="http://www.gwydiondylan.org/drm/drm_1.htm">The Dylan Reference Manual</A></STRONG> [<A HREF="http://www.fun-o.com/products/books.phtml#drm">paper, US$41.95</A>]

<DD><P>The official Dylan reference, available online or as a well-bound
softcover book. You won't be able to learn Dylan from this, but you can certainly
fill out your knowledge of the details. If you already know a smattering of
Dylan, and can only get one book, this is your best bet.</P>

<DT><STRONG><A HREF="http://www.harlequin.com/products/ads/dylan/doc/duim-guide/duim-guide-1.html">Building Applications Using DUIM</A></STRONG> (currently offline)

<DD><P>A tutorial on building GUIs in Dylan. DUIM (the Dylan User Interface
Manager) is a library designed by Harlequin for building portable
interfaces. We don't support this under Gwydion Dylan yet, but it would be
very nice to have. Note how well the basic primitives would map onto a
widget set like Gtk+.</P>

</DL>

<P>[ <A HREF="gdref.phtml">Documentation</A> ]</P>


<?php standard_footer(); ?>
