<?php
require "shared.inc";
standard_header("Mailing Lists");
?>

<P>We have a mailing list for the organization of development at <A
HREF="gd-hackers@randomhacks.com">gd-hackers@randomhacks.com</A>. If
you'd like to participate in development, or if you are a user of
Gwydion Dylan, feel free to join by sending mail to <A
HREF="mailto:majordomo@randomhacks.com">majordomo@randomhacks.com</a>
with <tt>subscribe&nbsp;gd-hackers</tt> in the body. Bugs can be
submitted to <A
HREF="mailto:gd-bugs@randomhacks.com">gd-bugs@randomhacks.com</a>.</P>

<?php standard_footer(); ?>
