<?php
require "shared.inc";
standard_header("Mailing Lists");
?>

<P>We have several mailing lists. To subscribe, please send mail to
the appropriate subscription address by clicking on the subscribe link.</P>

<DL>

<DT>
<STRONG><A HREF="http://www.gwydiondylan.org/cgi-bin/mailman/listinfo/gd-announce">gd-announce</A></STRONG>
<a href="mailto:gd-announce-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="http://www.gwydiondylan.org/pipermail/gd-announce">archives</a>

<DD><P>Find out about new Gwydion Dylan releases! This is an extremely
low-traffic list reserved for announcements. (If you subscribe to
gd-hackers below, you don't need to subscribe to this list, too.)</P>

<DT>
<STRONG><A HREF="mailto:gd-hackers@gwydiondylan.org">gd-hackers</A></STRONG>
<a href="mailto:gd-hackers-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="http://www.gwydiondylan.org/pipermail/gd-hackers">archives</a>

<DD><P>Our public development list. Here's where we talk about improving
Gwydion Dylan and co-ordinate most of our development work. (A very small
bit happens behind the scenes.) If you want to contribute, this is the
place to start. Just post a message explaining what you'd like to do, and
see what other developers suggest. You can post small patches to the list,
or upload big ones to our FTP site. Lurkers are also welcome, too!</P>

<!--
<P>Please respect this list; we use it to get work done and don't
appreciate random noise. We <EM>will</EM> unsubscribe you if you're rude or
ignore requests to stay on topic.</P>
-->

<DT>
<STRONG><A HREF="mailto:gd-chatter@gwydiondylan.org">gd-chatter</A></STRONG>
<a href="mailto:gd-chatter-request@gwydiondylan.org?subject=subscribe">subscribe</a>
<a href="http://www.gwydiondylan.org/pipermail/gd-chatter">archives</a>


<DD><P>This list contains nothing but CVS and JitterBug output. This is for
hardcore developers who need to know everything that's going on.</P>

<DT>
<STRONG><A HREF="news:comp.lang.dylan">comp.lang.dylan</a></strong>

<dd><p>This is the newsgroup dedicated to the discussion of Dylan</p>

<!-- Not yet supported
<DT><INPUT TYPE="CHECKBOX" NAME="INFO-DYLAN">
<STRONG><A HREF="mailto:info-dylan@harlequin.co.uk">info-dylan</A></STRONG>
[Archive]

<DD><P>We don't host this list; <A
HREF="http://www.harlequin.com/">Harlequin</A> does. It is gatewayed to
the newsgroup <A HREF="news:comp.lang.dylan">comp.lang.dylan</A>, and is a
good place to discuss the Dylan programming language.</P>
-->

</DL>


<?php standard_footer(); ?>
