<?php
require "shared.inc";
standard_header("Gwydion Dylan Maintainers");
?>

<P>The credit for Gwydion Dylan should go to the <A
HREF="http://legend.gwydion.cs.cmu.edu/">Gwydion Group at
CMU</A>, which is currently researching advanced development
environments. They wrote Melange, d2c, the standard Dylan libraries and
many useful tools.</P>

<P>The current maintainers of Gwydion are Dylan enthusiasts who hope to
fight bit rot and add new features to the compiler. We are (in alphabetical
order):</P>

<H3>Core Team</H3>

<P><STRONG>Andreas Bogk</STRONG></P>
<UL>
<LI>SuSE and libc5 maintainer
<LI>FTP and CVS administrator
</UL>

<P><STRONG>Peter S. Housel</STRONG></P>
<UL>
<LI>FreeBSD maintainer
<LI>Low-level C interface
</UL>

<P><STRONG>Eric Kidd</STRONG></P>
<UL>
<LI>RedHat 5.1/x86 and lib6 maintainer
<LI>Webmaster
<LI>Melange and Gtk+ weenie
</UL>

<H3>Major Contributors</H3>

<P><STRONG>Jeff Dubrule</STRONG></P>
<UL>
<LI>GDB Dylan Support
<LI>getopt library
</UL>

<P><STRONG>Peter Hinely</STRONG></P>
<UL>
<LI>Mindy for the BeOS
</UL>

<P><STRONG>Matthias Hoelzl</STRONG></P>
<UL>
<LI>Really impressive compiler improvements
</UL>

<P><STRONG>Ole J. Tetlie</STRONG></P>
<UL>
<LI>Solaris and Debian maintainer
<LI>getopt library
</UL>

<P>If you'd like to join us, check out the <A HREF="lists.phtml">mailing list</A>.</P>

<?php standard_footer(); ?>

