<?php
require "shared.inc";
standard_header("Gwydion Dylan Maintainers");
?>

<P>The credit for Gwydion Dylan should go to the <A
HREF="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">Gwydion
Group at CMU</A>, which is currently researching advanced development
environments. They wrote Melange, d2c, the standard Dylan libraries and
many useful tools.</P>

<P>The current maintainers of Gwydion are Dylan enthusiasts who hope to
fight bit rot and add new features to the compiler. We are (in alphabetical
order):</P>

<H3>Core Team</H3>

<P><STRONG>Andreas Bogk</STRONG></P>
<UL>
<LI>SuSE and libc5 maintainer
<LI>FTP and CVS administrator
</UL>

<P><STRONG>Matthias Hoelzl</STRONG></P>
<UL>
<LI>Really impressive compiler improvements
<LI>Standard libraries
<LI>New Gtk+ bindings
</UL>

<P><STRONG>Peter S. Housel</STRONG></P>
<UL>
<LI>FreeBSD maintainer
<LI>Low-level C interface
</UL>

<P><STRONG>Eric Kidd</STRONG></P>
<UL>
<LI>RedHat 5.1/x86 and lib6 maintainer
<LI>Webmaster
<LI>Melange and Gtk+ weenie
</UL>

<P>The core team acts as an advisory board. None of us have enough time to
act as the "authoritative developer" the way Linus Torvalds does, so we
split the responsibility.</P>

<P>We don't do all of the work ourselves, though. Our major contributors
are tackling several large and important projects.</P>

<H3>Major Contributors</H3>

<P><STRONG>Jeff Dubrule</STRONG></P>
<UL>
<LI>64-bit Mindy and d2c
<LI>Other enhancements
<LI>Debugging support
</UL>

<P><STRING>Tom Emerson</STRONG></P>
<UL>
<LI>Solaris 2.x maintainer
<LI>Sundry libraries (operating-system, file-system, date, and regexp)
<LI>Internationalization and Localization
<LI>Complete build system redesign
</UL>

<P><STRONG>Peter Hinely</STRONG></P>
<UL>
<LI>Mindy for the BeOS
<LI>Performance improvements
</UL>

<P>If you'd like to join us, check out the <A HREF="lists.phtml">mailing
list</A>.</P>

<?php standard_footer(); ?>

