<?php
require "shared.inc";
standard_header("Interfacing with C");
?>

<P>For Gwydion to be useful, it must interface seamlessly with C. Most
interesting libraries are written in C, including all of the significant
APIs for Unix systems. Ideally, it should be as easy to call a C function
from a Dylan program as it is to call one from a C program.</P>

<P>The original Gwydion developers at CMU wrote a nifty tool called
Melange. It parses C header files and automatically generates interfaces in
Dylan. We've been slowly enhancing this to handle more complicated header
files, and stomping all the bugs which we find along the way.</P>

<p>On the way de decided to rewrite parts of melange, and a new
project, called pidgin, was started. It has a working C header
parser. but it's missing the code generation part. Adding that is not
that difficult, if you're looking for a way to help our project,
that's your chance. Contact us on the <a href=lists.phtml>gd-hackers
mailing list</a>for details.</p>

<p>We already have working callbacks from C to Dylan code, on x86 and
PPC even with callbacks to closures.</p>

<?php
begin_progress_table();
progress("Improve parser", 9);
progress("Write interface generation code", 0);
end_progress_table();
?>

<?php standard_footer(); ?>
