<?php
require "shared.inc";
standard_header("What's New");
?>

<DL>

<DT><STRONG>Mailing lists back up (07 Oct 1999)</strong></dt> <dd><p>
You might have noticed it, the Gwydion Dylan mailing lists were down
during the last weeks. We haven't recovered the subscriber information
yet, so you'll have to resubscribe, but the mailing lists are
functional again. Addresses have changed, see <a
href="lists.phtml">here</a> for details.</p>

<DT><STRONG>BeOS port of Gwydion Dylan (09 Sep 1999)</strong></dt>
<dd><p> Chris Double has ported Gwydion Dylan to the Be Operating
System. You can find installation instructions on his <a
href="http://www.double.co.nz/beos">page</a> and download the binary
either from there, from <a
href="http://www.bebits.com/app/348">BeBits</a> or from the
contributions directory of one of our mirrors.
</p>



<DT><STRONG>Build Problems with 2.3.2 (24 Aug 1999)</strong></dt>
<dd><p> As various people have reported, version 2.3.2 cannot be
compiled with older versions of itself. This is of course a bug, and
that's why we have a new version, 2.3.2a, on the <a
href="downloading.phtml">FTP</a> servers. Just apply the patch in your
source tree, or download the newest version.
</p>


<DT><STRONG>Development Release 2.3.2 (22 Aug 1999)</strong></dt>
<dd><p>Today the latest development version of Gwydion Dylan, 2.3.2,
has been released. You can get it from the <a
href="downloading.phtml">usual</a> places. The long version of the
announcement is <a href="release-2.3.2.phtml">here</a>, the main new
feature being shared library support on some platforms. Please note
that our list server is down, so please send bug reports directly to
<a href="mailto:gd@andreas.org">Andreas Bogk</a>.</p>

<DT><STRONG>PowerMacMindy 2.3.1r2 released (28 Jul 1999)</strong></dt>
<dd><p>Rob Myers, the maintainer of the MacOS port of mindy (the
interpreter part of Gwydion Dylan), released a new version of mindy
for PowerMacs. New amongst others are shared library support and
nearly-working streams. You can get the package in the MacOS directory
of one of our <a href="downloading.phtml">mirror sites</a>.
</p>

<DT><STRONG>Development Release 2.3.1 (8 Jun 1999)</strong></dt>
<dd><p>Today the latest development version of Gwydion Dylan, 2.3.1,
has been released. You can get it from the <a href="downloading.phtml">usual</a>
places. The long version of the announcement is <a href="release-2.3.1.phtml">here</a>.</p>

<DT><STRONG>OpenBSD/Sparc Port, xformat library (29 Apr
1999)</STRONG></DT> <DD><P>Brad Dominy has ported Gwydion Dylan to
OpenBSD. Version 2.2.0 can be found on the usual <A
HREF="downloading.phtml">mirror</A> sites in the contributions
directory. Future versions such as the upcoming 2.3.1 development
version will of course include the patches.<P> Also in the
contributions directory is David Lichteblaus port of the Common Lisp
format library to Dylan, which is way more powerful than the native
format library.<p>

<DT><STRONG>PCRE interface library 0.1 released (6 Apr 1999)</STRONG></DT>
<DD><P>The initial version of the PCRE (Perl Compatible Regular Expressions)
interface is available from the contributions directory of any of our
<A HREF="downloading.phtml">mirror</A> sites. This version provides a
one-to-one mapping from the native PCRE C API into Dylan. The next release
will extend this greatly.</P>

<DT><STRONG>Mac version of mindy available (1 Apr 1999)</STRONG></DT>

<DD><P>Due to the efforts of Rob Myers, mindy, the Dylan interpreter
from the Gwydion Dylan package, is available for the Macintosh. You
can get it from usual location, the contributions directory of any of
our <A HREF="downloading.phtml">mirror</A> sites.</P>

<DT><STRONG>MySQL interface library 0.1 released (11 Mar 1999)</STRONG></DT>

<DD><P>The MySQL interface is still work in progress, but all the
low-level stuff is there, and it has been used successfully together
with the cgi-lib. You can download it from the contrib directory of any
<A HREF="downloading.phtml">mirror</A> site.</P>

<DT><STRONG>Peter Hinely's CGI Library Updated (12 Feb 1999)</STRONG></DT>

<DD><P>Peter Hinely has released a new version of his CGI library. You can
download it from the contrib directory of any <A
HREF="downloading.phtml">mirror</A> site.</P>

<DT><STRONG>Gwydion Dylan 2.2.0 Released (7 Feb 1999)</STRONG></DT>

<DD><P>We've been busy talking with Harlequin about language
standardization, but 2.2.0 is finally ready! You can download it from any
of our <A HREF="downloading.phtml">mirrors</A>. See the <A
HREF="release-2.2.phtml">official announcement</A> for more
information.</P>

<P>This represents over nine months of work and the labors of many
volunteers. Thank you to everyone who helped out!</P>

<DT><STRONG>Gwydion Dylan 2.1.3 Released (9 Jan 1999)</STRONG></DT>

<DD><P>We're almost there! Gwydion Dylan 2.1.3 is the final development
release before 2.2. Barring any unexpected bugs, we'll rerelease in a week
or two as the official 2.2.</P>

<P>New features include many bug fixes, a new parse-arguments library and
brand new man pages.</P>

<DT><STRONG>Code Freeze for Gwydion Dylan 2.2 (24 Dec 1998)</STRONG></DT>

<DD><P>We've frozen the code in CVS in anticipation of our forthcoming 2.2
release. Look for a final test version, and then the real thing!</P>

<DT><STRONG>Gwydion Dylan Status Report (24 Dec 1998)</STRONG></DT>

<DD>
<P>We're pushing towards a code freeze now. A few outstanding bugs need
fixing (see the <STRONG>critical</STRONG> section in the bug tracker), bits
of Melange need further study, and our documentation is still not
completely resolved.</P>

<P>Jeff Dubrule has ported Mindy to run on a 64-bit system (RedHat 5.2
Alpha), and has started work on d2c. (These ports will not be included
in 2.2.) Peter Housel and Matthias Hoelzl have been stomping bugs left and
right, and Eric Kidd has rewritten getopt and cooked up some man pages.
Andreas has been working to make Melange play nicely with Gtk+, and Peter
Hinely has been helping edit our documentation. Shaleh has bootstrapped d2c
under Debian, and should have debs sometime soon.</P>
</DD>

<DT><STRONG>Gwydion Dylan 2.1.2 Released (1 Dec 1998)</STRONG></DT>

<DD><P>
  The feature freeze for 2.2 is now in effect. We're closing out our
  critical bugs, working on documentation, and breaking one or two small
  things which should be done <EM>before</EM> we have users.
</P></DD>

<DT><STRONG>Gwydion Dylan 2.1 1998-09-16</STRONG></DT>

<DD><P>
  This month's snapshot includes a LinuxPPC port by Andreas Bogk, new
  Solaris binaries from Ole Tetlie, C-to-Dylan callback support by Peter
  Housel and a vastly improved Emacs dylan-mode courtesy of Harlequin, Ltd
  (and others). Peter Housel has also worked extensively on cleaning up and
  adding to the documentation.
</P></DD>

<DT><STRONG>Gwydion Dylan 2.1 1998-08-17</STRONG></DT>

<DD><P>
  The current release has been prepared by a group of volunteers. It
  includes improved FreeBSD support and a better build system. It can also
  parse most of the standard Linux C headers and automatically generate
  Dylan interfaces.
</P></DD>
</DL>

<P>[ <A HREF="lists.phtml">Mailing List Archives</A> ]</P>

<?php standard_footer(); ?>
