<?php
require "shared.inc";
standard_header("What's New");
?>

<DL>
<DT><STRONG>Gwydion Dylan 2.1 1998-09-16</STRONG></DT>

<DD><P>
  This month's snapshot includes a LinuxPPC port by Andreas Bogk, new
  Solaris binaries from Ole Tetlie, C-to-Dylan callback support by Peter
  Housel and a vastly improved Emacs dylan-mode courtesy of Harlequin, Ltd
  (and others). Peter Housel has also worked extensively on cleaning up and
  adding to the documentation.
</P></DD>

<DT><STRONG>Gwydion Dylan 2.1 1998-08-17</STRONG></DT>

<DD><P>
  The current release has been prepared by a group of volunteers. It
  includes improved FreeBSD support and a better build system. It can also
  parse most of the standard Linux C headers and automatically generate
  Dylan interfaces.
</P></DD>
</DL>

<?php standard_footer(); ?>
