<?php
require "shared.inc";
standard_header("What's New");
?>

<DL>

<DT><STRONG>Peter Hinely's CGI Library Updated (12 Feb 1999)</STRONG></DT>

<DD><P>Peter Hinely has released a new version of his CGI library. You can
download it from the contrib directory of any <A
HREF="downloading.phtml">mirror</A> site.</P>

<DT><STRONG>Gwydion Dylan 2.2.0 Released (7 Feb 1999)</STRONG></DT>

<DD><P>We've been busy talking with Harlequin about language
standardization, but 2.2.0 is finally ready! You can download it from any
of our <A HREF="downloading.phtml">mirrors</A>. See the <A
HREF="release-2.2.phtml">official announcement</A> for more
information.</P>

<P>This represents over nine months of work and the labors of many
volunteers. Thank you to everyone who helped out!</P>

<DT><STRONG>Gwydion Dylan 2.1.3 Released (9 Jan 1999)</STRONG></DT>

<DD><P>We're almost there! Gwydion Dylan 2.1.3 is the final development
release before 2.2. Barring any unexpected bugs, we'll rerelease in a week
or two as the official 2.2.</P>

<P>New features include many bug fixes, a new parse-arguments library and
brand new man pages.</P>

<DT><STRONG>Code Freeze for Gwydion Dylan 2.2 (24 Dec 1998)</STRONG></DT>

<DD><P>We've frozen the code in CVS in anticipation of our forthcoming 2.2
release. Look for a final test version, and then the real thing!</P>

<DT><STRONG>Gwydion Dylan Status Report (24 Dec 1998)</STRONG></DT>

<DD>
<P>We're pushing towards a code freeze now. A few outstanding bugs need
fixing (see the <STRONG>critical</STRONG> section in the bug tracker), bits
of Melange need further study, and our documentation is still not
completely resolved.</P>

<P>Jeff Dubrule has ported Mindy to run on a 64-bit system (RedHat 5.2
Alpha), and has started work on d2c. (These ports will not be included
in 2.2.) Peter Housel and Matthias Hoelzl have been stomping bugs left and
right, and Eric Kidd has rewritten getopt and cooked up some man pages.
Andreas has been working to make Melange play nicely with Gtk+, and Peter
Hinely has been helping edit our documentation. Shaleh has bootstrapped d2c
under Debian, and should have debs sometime soon.</P>
</DD>

<DT><STRONG>Gwydion Dylan 2.1.2 Released (1 Dec 1998)</STRONG></DT>

<DD><P>
  The feature freeze for 2.2 is now in effect. We're closing out our
  critical bugs, working on documentation, and breaking one or two small
  things which should be done <EM>before</EM> we have users.
</P></DD>

<DT><STRONG>Gwydion Dylan 2.1 1998-09-16</STRONG></DT>

<DD><P>
  This month's snapshot includes a LinuxPPC port by Andreas Bogk, new
  Solaris binaries from Ole Tetlie, C-to-Dylan callback support by Peter
  Housel and a vastly improved Emacs dylan-mode courtesy of Harlequin, Ltd
  (and others). Peter Housel has also worked extensively on cleaning up and
  adding to the documentation.
</P></DD>

<DT><STRONG>Gwydion Dylan 2.1 1998-08-17</STRONG></DT>

<DD><P>
  The current release has been prepared by a group of volunteers. It
  includes improved FreeBSD support and a better build system. It can also
  parse most of the standard Linux C headers and automatically generate
  Dylan interfaces.
</P></DD>
</DL>

<P>[ <A HREF="lists.phtml">Mailing List Archives</A> ]</P>

<?php standard_footer(); ?>
