<?php
require "shared.inc";
standard_header("Current Projects");
?>

<P>Some of the projects we are working on:</P>

<UL>
<LI><A HREF="ports.phtml">Ports</A>
<LI><A HREF="melange.phtml">C Interface</A>
<LI><A HREF="gui.phtml">GTK+ Interface</A>
<LI><A HREF="packaging.phtml">Packaging</A>
<LI><A HREF="documentation.phtml">Documentation</A>
</UL>

<P><STRONG>Note</STRONG> that the status pages linked above are in
some cases several years out of date.</P>

<?php standard_footer(); ?>
