<?php
require "shared.inc";
standard_header("Current Projects");
?>

<P>We're working on a number of different projects at the moment:</P>

<UL>
<LI><A HREF="ports.phtml">Ports</A>
<LI><A HREF="melange.phtml">C Interface</A>
<LI><A HREF="gui.phtml">GTK+ Interface</A>
<LI><A HREF="packaging.phtml">Packaging</A>
<LI><A HREF="documentation.phtml">Documentation</A>
</UL>


<?php standard_footer(); ?>
