<?php
require "shared.inc";

if ($REQUEST_METHOD == "GET") {
  standard_header("Software Map - New Project");
?>

<form method=post action=register-new-project.phtml>
<p>Name: <input name=name type=text maxlength=50 size=50>
<p>Version: <input name=version type=text maxlength=20 size=20>
<p>Short Description:<br>
<textarea name=description cols=70, rows=3 ></textarea>
<input type=submit>
</form>

<?
} else {
  standard_header("Software Map - Project submitted");

  $db = db_connect();

  $id = mysql_result(mysql_query("select * from softmap_next_id",$db),0,0);
  
  $query = 'insert into softmap values (' . $id . ', "'.
	addslashes($name).'", "'.addslashes($version).'", NOW(), "' . 
	addslashes($description).'")';

  mysql_query($query, $db);
  if (!($err = mysql_error())) {
    mysql_query('update softmap_next_id set next_id = ' . ($id + 1), $db);
  }	
  if ($err = mysql_error()) {
    echo "MySQL error occurred: " . $err ."<p>Please notify <a href=mailto:igor@pobox.com>Jeff Dubrule</a>.";
    echo "<p>query=".$query;
  } else {
    echo "Project submitted.<p><a href=software-map.phtml>Back to software map</a>";
    echo "<p>query=".$query;
  }   
}

standard_footer(); 

?>
