<?php
require "shared.inc";
standard_header("Release 2.3.2 (Development version)");
?>

<p><strong>August 22 1999</strong> --Gwydion Dylan is a portable, optimizing Dylan
compiler. It was originally written by the Gwydion Group at CMU and is now
maintained by volunteers.  Eventually, we'd like Gwydion Dylan to become a
top-notch tool for building complicated applications written in a mix of
Dylan and C.</p>

<p>The current release is a development release. This means that the
different projects we're working on are not finished, not documented
or buggy. Nevertheless lots of bugs have been fixed and functionality
added, so if you don't mind a little adventure, this release is
definitely for you. For details, see the NEWS file in the source
distribution.</p>

<p>The major new feature of 2.3.2 is support for shared libraries on selected platforms.</p>

<H3>More Information About Gwydion Dylan:</H3>

<UL>
<LI><A HREF="http://www.gwydiondylan.org/">Volunteers' website</A>
<LI><A HREF="http://www.gwydiondylan.org/downloading.phtml">Downloading</A>
<LI><A HREF="http://www.gwydiondylan.org/lists.phtml">Mailing lists</A>
<LI><A HREF="http://www.gwydiondylan.org/learning.phtml">Learning Dylan</A>
<LI><A HREF="mailto:gd-bugs@randomhacks.com">Bug reports</A>                 
<LI><A HREF="news:comp.lang.dylan">Newsgroup</A>
</UL>

<H3>Other Dylan Releases</H3>

<UL>
<LI><A HREF="http://www.harlequin.com/devtools/dylan">Harlequin Dylan for Windows</A>
<LI>Apple Dylan (no longer available)
<LI><A HREF="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">Gwydion Dylan 2.0 from CMU</A>
</UL>

<P><SMALL>Dylan is a trademark of Apple Computer, Incorporated. All other
trademarks are property of their respective owners.</SMALL></P>

<?php standard_footer(); ?>
