<?php
require "shared.inc";
standard_header("Release 2.2 (Technology Preview)");
?>

<P><STRONG>7 Feb 1999 --</STRONG> Gwydion Dylan is a portable, optimizing
Dylan<tm> compiler. It was originally written by the Gwydion Group at CMU
and is now maintained by volunteers.  Eventually, we'd like Gwydion Dylan
to become a top-notch tool for building complicated applications written in
a mix of Dylan and C.</P>

<P>The current release is a "technology preview". The compiler is quite
mature; the most inconvenient bugs have been stomped; and a fair amount of
documentation has been written. Realistically, 2.2 could be used for
learning Dylan or building command-line applications.</P>

<P>The Dylan programming language was designed with three goals in mind:
high performance, rapid prototyping and ease of use. Recently, the Gwydion
volunteers and Harlequin's Dylan team have been working a fourth goal:
seamless integration of Dylan programs with existing C code.</P>

<P>Dylan looks a bit like Pascal, C or Java. In general, experienced
programmers should be able to learn the basics in a week and pick up the
rest as they go along. Novice programmers should find Dylan no harder to
learn than Java (although less documentation is available). Dylan supports
imperative, functional, and object-oriented programming. It also provides
many LISP-like features, including multi-methods, hygienic macros, closures
and optional dynamic types.</P>

<P>Dylan's combination of familiar syntax and advanced features make it a
good choice for teaching computer science. Its emphasis on performance and
sheer expressive power should appeal to application developers (at least
once enough supporting tools become available). C integration, when
finished, will allow the use of existing libraries and legacy code.</P>

<P>Current development priorities include source-level compatibility with
Harlequin Dylan, improved compiler performance, and support for GUI
programming using DUIM, Gtk+, Gnome and possibly KDE or Motif. Feedback and
interesting patches are eagerly welcomed!</P>

<H3>More Information About Gwydion Dylan:</H3>

<UL>
<LI><A HREF="http://www.gwydiondylan.org/">Volunteers' website</A>
<LI><A HREF="http://www.gwydiondylan.org/downloading.phtml">Downloading</A>
<LI><A HREF="http://www.gwydiondylan.org/lists.phtml">Mailing lists</A>
<LI><A HREF="http://www.gwydiondylan.org/learning.phtml">Learning Dylan</A>
<LI><A HREF="mailto:gd-bugs@randomhacks.com">Bug reports</A>                 
<LI><A HREF="news:comp.lang.dylan">Newsgroup</A>
</UL>

<H3>Other Dylan Releases</H3>

<UL>
<LI><A HREF="http://www.harlequin.com/devtools/dylan">Harlequin Dylan for Windows</A>
<LI>Apple Dylan (no longer available)
<LI><A HREF="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">Gwydion Dylan 2.0 from CMU</A>
</UL>

<P><SMALL>Dylan is a trademark of Apple Computer, Incorporated. All other
trademarks are property of their respective owners.</SMALL></P>

<?php standard_footer(); ?>
