<?php
require "shared.inc";
standard_header("Release 2.3.1 (Development version)");
?>

<p><strong>June 08 1999</strong> --Gwydion Dylan is a portable, optimizing Dylan
compiler. It was originally written by the Gwydion Group at CMU and is now
maintained by volunteers.  Eventually, we'd like Gwydion Dylan to become a
top-notch tool for building complicated applications written in a mix of
Dylan and C.</p>

<p>The current release is a development release. This means that the
different projects we're working on are not finished, not documented
or buggy. Nevertheless lots of bugs have been fixed and functionality
added, so if you don't mind a little adventure, this release is
definitely for you. For details, see the NEWS file in the source
distribution.</p>

<p>The Dylan programming language was designed with three goals in mind:
high performance, rapid prototyping and ease of use. Recently, the
Gwydion volunteers and Harlequin's Dylan team have been working a
fourth goal: seamless integration of Dylan programs with existing C
code. In order to achieve this, we have been working on the
common-dylan library, which is intended to give 100% source code
compatibility, as well as a HD-compatible c-ffi library. We're also
working on pidgin, a new tool to parse header files and automatically
generate C bindings from that. This is not complete, but you can see
the beginnings in this release.</p>

<H3>More Information About Gwydion Dylan:</H3>

<UL>
<LI><A HREF="http://www.gwydiondylan.org/">Volunteers' website</A>
<LI><A HREF="http://www.gwydiondylan.org/downloading.phtml">Downloading</A>
<LI><A HREF="http://www.gwydiondylan.org/community.phtml">Community Resources</A>
<LI><A HREF="http://www.gwydiondylan.org/learning.phtml">Learning Dylan</A>
<LI><A HREF="mailto:gd-bugs@randomhacks.com">Bug reports</A>                 
</UL>

<H3>Other Dylan Releases</H3>

<UL>
<LI><A HREF="http://www.harlequin.com/devtools/dylan">Harlequin Dylan for Windows</A>
<LI>Apple Dylan (no longer available)
<LI><A HREF="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">Gwydion Dylan 2.0 from CMU</A>
</UL>

<P><SMALL>Dylan is a trademark of Apple Computer, Incorporated. All other
trademarks are property of their respective owners.</SMALL></P>

<?php standard_footer(); ?>
