<?php
require "shared.inc";
standard_header("Release 2.3.4");
?>

<p><strong>Nov 30 2000</strong> Gwydion Dylan is a portable, optimizing Dylan
compiler. It was originally written by the Gwydion Group at CMU and is now
maintained by volunteers.  Eventually, we'd like Gwydion Dylan to become a
top-notch tool for building complicated applications written in a mix of
Dylan and C.</p>

<p>With the port of d2c to MacOS X and Win32/Cygwin, Gwydion Dylan now
fully supports all of the platforms in common use. There's even a
library that wraps MacOS' Carbon API. Our documentation is getting
better, and there are fewer and fewer bugs.

<H3>More Information About Gwydion Dylan:</H3>

<UL>
<LI><A HREF="http://www.gwydiondylan.org/">Volounteers' website</A>
<LI><A HREF="http://www.gwydiondylan.org/downloading.phtml">Downloading</A>
<LI><A HREF="http://www.gwydiondylan.org/lists.phtml">Mailing lists</A>
<LI><A HREF="http://www.gwydiondylan.org/learning.phtml">Learning Dylan</A>
<LI><A HREF="mailto:gd-bugs@gwydiondylan.org">Bug reports</A>                 
<LI><A HREF="news:comp.lang.dylan">Newsgroup</A>
</UL>

<?php standard_footer(); ?>
