<!--

    This is default template file for mnoGoSearch-php 3.1
    (C) 1999, mnoGoSearch developers team <devel@search.udm.net>

    Please rename to search.htm and edit as desired. 
    See doc/README.templates for detailed information.
    You may want to keep the original file for future reference.
    
    WARNING: Please keep the file chmod 600 to protect your passwords!
    
-->
<!--variables
DBAddr  pgsql://mnogosearch@/mnogosearch/
DBMode  crc-multi
IspellMode db

# Uncomment this line to enable query tracking facility
#TrackQuery no

#  Uncomment this line if you do not want to detect and show clones
#Clones	no

# Hilight found word syntax. 
# HLBeg is prepended before the word. Default is <b>
# HLEnd is appended after the word. Default is </b>
#HLBeg <font color="#905050">
#HLEnd </font>

-->

<!--top-->
<HTML>
<HEAD>
 <TITLE>mnoGoSearch: $Q</TITLE>
</HEAD>

<body BGCOLOR="#FFFFFF" LINK="#0050A0" VLINK="#0050A0" ALINK="#0050A0">
<center>

<FORM METHOD=GET ACTION="$A">
<table bgcolor=#eeeee0 order=1 width=100%>
<tr><td>
<BR>
<INPUT TYPE="hidden" NAME="ps" VALUE="10">
Search for: <INPUT TYPE="text" NAME="q" SIZE=50 VALUE="$Q">
<INPUT TYPE="submit" VALUE="Search!"><BR>

Results per page:
<SELECT NAME="ps">
<OPTION VALUE="10" SELECTED="$ps">10
<OPTION VALUE="20" SELECTED="$ps">20
<OPTION VALUE="50" SELECTED="$ps">50
</SELECT>

Output format:
<SELECT NAME="o">
<OPTION VALUE="0" SELECTED="$o">Long
<OPTION VALUE="1" SELECTED="$o">Short
<OPTION VALUE="2" SELECTED="$o">URL
</SELECT>

Default query type:
<SELECT NAME="m">
<OPTION VALUE="and" SELECTED="$m">All
<OPTION VALUE="or" SELECTED="$m">Any
</SELECT>


<br>


Search through:
<SELECT NAME="ul">
<OPTION VALUE=""            SELECTED="$ul">Entire site
<OPTION VALUE="/docs/"    SELECTED="$ul">Docs
<OPTION VALUE="/files/"  SELECTED="$ul">Files
<OPTION VALUE="/servers/"   SELECTED="$ul">Servers
</SELECT>

Language:
<SELECT NAME="lang">
<OPTION VALUE=""	SELECTED="$lang">Any
<OPTION VALUE="en"	SELECTED="$lang">English
<OPTION VALUE="de"	SELECTED="$lang">German
</SELECT>


Restrict search:
<SELECT NAME="t">
<OPTION VALUE="" SELECTED="$g">All sites
<OPTION VALUE="1" SELECTED="$g">Sport
<OPTION VALUE="2" SELECTED="$g">Shopping
</SELECT>


</td></tr>

<!-- 'search with time limits' options -->
<!--
<TR><TD>
<TABLE CELLPADDING=2 CELLSPACING=0 BORDER=0>
<CAPTION>
Limit results to pages published within a specified period of time.<BR>
<FONT SIZE=-1><I>(Please select only one option)</I></FONT>
</CAPTION>
<TR> 
<TD VALIGN=center><INPUT TYPE=radio NAME="dt" VALUE="back" CHECKED></TD>
<TD><SELECT NAME="dp">
<OPTION VALUE="0" SELECTED="$dp">anytime
<OPTION VALUE="10M" SELECTED="$dp">in the last ten minutes
<OPTION VALUE="1h" SELECTED="$dp">in the last hour
<OPTION VALUE="7d" SELECTED="$dp">in the last week
<OPTION VALUE="14d" SELECTED="$dp">in the last 2 weeks
<OPTION VALUE="1m" SELECTED="$dp">in the last month
<OPTION VALUE="3m" SELECTED="$dp">in the last 3 months
<OPTION VALUE="6m" SELECTED="$dp">in the last 6 months
<OPTION VALUE="1y" SELECTED="$dp">in the last year
<OPTION VALUE="2y" SELECTED="$dp">in the last 2 years
</SELECT>
</TD>
</TR>
<TR>
<TD VALIGN=center><INPUT type=radio NAME="dt" VALUE="er">
</TD>
<TD><SELECT NAME="dx">
<OPTION VALUE="1" SELECTED="$dx">After
<OPTION VALUE="-1" SELECTED="$dx">Before
</SELECT>

or on

<SELECT NAME="dm">
<OPTION VALUE="0" SELECTED="$dm">January
<OPTION VALUE="1" SELECTED="$dm">February
<OPTION VALUE="2" SELECTED="$dm">March
<OPTION VALUE="3" SELECTED="$dm">April
<OPTION VALUE="4" SELECTED="$dm">May
<OPTION VALUE="5" SELECTED="$dm">June
<OPTION VALUE="6" SELECTED="$dm">July
<OPTION VALUE="7" SELECTED="$dm">August
<OPTION VALUE="8" SELECTED="$dm">September
<OPTION VALUE="9" SELECTED="$dm">October
<OPTION VALUE="10" SELECTED="$dm">November
<OPTION VALUE="11" SELECTED="$dm">December
</SELECT>
<INPUT TYPE=text NAME="dd" VALUE="$dd" SIZE=2 maxlength=2>
,
<SELECT NAME="dy" >
<OPTION VALUE="1990" SELECTED="$dy">1990
<OPTION VALUE="1991" SELECTED="$dy">1991
<OPTION VALUE="1992" SELECTED="$dy">1992
<OPTION VALUE="1993" SELECTED="$dy">1993
<OPTION VALUE="1994" SELECTED="$dy">1994
<OPTION VALUE="1995" SELECTED="$dy">1995
<OPTION VALUE="1996" SELECTED="$dy">1996
<OPTION VALUE="1997" SELECTED="$dy">1997
<OPTION VALUE="1998" SELECTED="$dy">1998
<OPTION VALUE="1999" SELECTED="$dy">1999
<OPTION VALUE="2000" SELECTED="$dy">2000
<OPTION VALUE="2001" SELECTED="$dy">2001
</SELECT>
</TD>
</TR>
<TR>
<TD VALIGN=center><INPUT TYPE=radio NAME="dt" VALUE="range">
</TD>
<TD>
Between
<INPUT TYPE=text NAME="db" VALUE="$db" SIZE=11 MAXLENGTH=11>
and
<INPUT TYPE=text NAME="de" VALUE="$de" SIZE=11 MAXLENGTH=11>
</TD>
</TR>
</TABLE>

</TD></TR>
-->	
<!-- end of stl options -->

<!-- categories stuff -->
<!--
<tr><td>$CP</td></tr>
<tr><td>$CS</td></tr>
<input type=hidden name=cat value="$cat">
-->
<!-- categories stuff end -->


</table>
</form>
</center>
<!--/top-->



<!--restop-->
Search Time: $SearchTime<br>
Search results:
<small>$W</small><HR>
Displaying documents $f-$l of total <B>$t</B> found.
<!--/restop-->
<!--res-->
<DL><DT>
<b>$DN.</b> <a href="$DU" TARGET="_blank"><b>$DT</b></a> [<b>$DR</b>]<DD>
$DE...<BR>$DY
<UL>
<li><A HREF="$DU" TARGET="_blank">$DU</A> ($DC) $DM, $DS bytes
$CL
</UL>
</DL>
<!--/res-->

<!--ftpres-->
<DL><DT>
<b>$DN.</b> <a href="$DU" TARGET="_blank"><b>$DT</b></a> [<b>$DR</b>]<DD>
<UL>
<li><A HREF="$DU" TARGET="_blank">$DU</A> ($DC) $DM, $DS bytes
$CL
</UL>
</DL>
<!--/ftpres-->

<!--resbot-->
<HR>
<CENTER>
$V
</CENTER>
<!--/resbot-->





<!--restop-->
Search Time: $SearchTime<br>
Search results:
<small>$W</small><HR>                                                                            
Displaying documents $f-$l of total <B>$t</B> found.
<!--/restop-->
<!--res-->
<DL><DT>
<b>$DN.</b> <a href="$DU" TARGET="_blank"><b>&nbsp; $DT</b></a> [<b>$DR</b>]<DD>
</DL>
<!--/res-->
<!--resbot-->
<HR>
<CENTER>
$V
</CENTER>
<!--/resbot-->



<!--restop-->
Search Time: $SearchTime<br>
Search results:
<small>$W</small><HR>
Displaying documents $f-$l of total <B>$t</B> found.
<!--/restop-->
<!--res-->
<DL><DT>
<b>$DN.</b> <a href="$DU" TARGET="_blank"><b>$DU</b></a> [<b>$DR</b>]<DD>
</DL>
<!--/res-->
<!--resbot-->
<HR>
<CENTER>
$V
</CENTER>
<!--/resbot-->




<!--clone-->
<li><A HREF="$DU" TARGET="_blank">$DU</A> ($DC) $DM
<!--/clone-->

<!--navigator-->
<TABLE BORDER=0><TR>$NL $NB $NR</TR></TABLE>
<!--/navigator-->

<!--navleft-->
<TD><A HREF="$NH">Prev</A></TD>
<!--/navleft-->

<!--navleft_nop-->
<TD><FONT COLOR="#707070">Prev</FONT></TD>
<!--/navleft_nop-->

<!--navbar1-->
<TD><A HREF="$NH">$NP</A></TD>
<!--/navbar1-->

<!--navbar0-->
<TD>$NP</TD>
<!--/navbar0-->

<!--navright-->
<TD><A HREF="$NH">Next</TD>
<!--/navright-->

<!--navright_nop-->
<TD><FONT COLOR="#707070">Next</FONT></TD>
<!--/navright_nop-->


<!--notfound-->
Search Time: $SearchTime<br>
Search results:
<small>$W</small><HR>
<CENTER>
Sorry, but search returned no results.<P>
<I>Try to produce less restrictive search query.</I>
</CENTER>
You can try to search this words: $SDX<br>
<HR>
<!--/notfound-->

<!--error-->
<CENTER>
<FONT COLOR="#FF0000">An error occured!</FONT>
<P><B>$E</B>
</CENTER>
<!--/error-->

<!--noquery-->
<FONT COLOR=red>You should give at least one word to search for.</FONT>
<!--/noquery-->



<!--bottom-->
<HR>
<center>
<img src="http://search.mnogo.ru/img/udm.gif">
<font size="-1">Powered by <a href="http://search.mnogo.ru/">mnoGoSearch</a></font><br>
<p>
</BODY>
</HTML>
<!--/bottom-->
