<?php
require "shared.inc";
?>

<?php
if(getenv('REQUEST_METHOD') == "GET") {
  standard_header("Submit News");
?>

<form method=post action=submit-news.phtml>
Headline:
<br>
<input name=headline type=text>
<br>
<br>
Message body:
<br>
<textarea name=body wrap=virtual cols=70 rows=12></textarea>
<br>
<br>
<input type=submit>
</form>

<?php
} else {
    standard_header("News submitted");

    $db = mysql_connect(":/tmp/mysql.sock",'www-post','gwydion-post');
    mysql_select_db("gwydion", $db);

    $headline = $_POST['headline'];
    $body = $_POST['body'];
    $query = 'insert into news values (NOW(),"'.$headline.'","'.$body.'","andreas","andreas",0)';
    $res = mysql_query($query, $db);
    $err = mysql_error();
    if($err) {
      echo "MySQL error occurred. Please notify <a href=andreas@andreas.org>Andreas</a>.";
    } else {
      echo "News submitted.<p>";
    }	
}

standard_footer();

?>
