<?php
require "shared.inc";
?>

<?php
if($REQUEST_METHOD == "GET") {
  standard_header("Submit News");
?>

<form method=post action=submit-news.phtml>
Headline:
<br>
<input name=headline type=text>
<br>
<br>
Message body:
<br>
<textarea name=body wrap=virtual cols=70 rows=12></textarea>
<br>
<br>
<input type=submit>
</form>

<?php
} else {
    standard_header("News submitted");

    $db = mysql_connect("localhost","gwydion","");
    mysql_select_db("gwydion");

    $query = 'insert into news values (NOW(),"'.addslashes($headline).'","'.addslashes($body).'","andreas","andreas",0)';
    $res = mysql_query($query, $db);
    $err = mysql_error();
    if($err) {
      echo "MySQL error occurred. Please notify <a href=andreas@andreas.org>Andreas</a>.";
    } else {
      echo "News submitted.<p>";
    }	
}

standard_footer();

?>