<?php
require "shared.inc";
standard_header("Projects Using Dylan");
?>

<P>Gwydion Dylan isn't just useful for writing Dylan compilers and tools.  This is a set of links to various projects using Dylan for their development.</P>

<DL>

<DT>
<STRONG><A HREF="http://sourceforge.net/projects/dylanlibs">Dylanlibs Project</A></STRONG>
<DD><P>Chris Double has created a set of libraries and utilities useful with Gwydion Dylan and Functional Developer.</P>

<DT>
<DT>
<STRONG><A HREF="http://www.functionalobjects.com">Functional Developer</A></STRONG>
<DD><P>Functional Developer is a high-quality Dylan programming environment developed in Dylan.  Windows and Linux versions are now available.</P>

<DT>
<STRONG><A HREF="http://monday.sourceforge.net">Monday</A></STRONG>
<DD><P>The Monday project includes a literate programming system and
libraries written in Dylan.</P>

</DL>


<?php standard_footer(); ?>
