<?php
require "shared.inc";
standard_header("Projects Using Dylan");
?>

<P>Open Dylan and Gwydion Dylan are both written in Dylan, but they aren't just
useful for writing Dylan compilers and tools.  This is a set of links to
various projects using Dylan for their development.</P>

<DL>

<DT>
<STRONG><A HREF="http://sourceforge.net/projects/dylanlibs">Dylanlibs Project</A></STRONG>
<DD><P>Chris Double has created a set of libraries and utilities useful with Gwydion Dylan and Open Dylan.</P>

<DT>
<STRONG><A HREF="http://monday.sourceforge.net">Monday</A></STRONG>
<DD><P>The Monday project includes a literate programming system and
libraries written in Dylan.</P>

<dt><strong><a href="http://www.gwydiondylan.org/koala/">Koala</a></strong></dt>
<dd>The Koala web server with Dylan Server Pages and XML-RPC.</dd>

</DL>


<?php standard_footer(); ?>
