module: dylan-user

define module dylan-rep
   use common;

   export
      <documentable-api-element>, <named-api-element>, <source-name>,
      <library>, <known-library>, <unknown-library>,
      <module>, <local-module>, <imported-module>,
      <binding>, <local-binding>, <imported-binding>,
      <definition>, <class-defn>, <generic-defn>, <function-defn>,
         <constant-defn>, <variable-defn>, <macro-defn>,
      <explicit-class-defn>, <explicit-generic-defn>, <implicit-generic-defn>,
      <slot>, <initable-slot>, <inherited-slot>, <accessor-slot>, <instance-slot>,
         <class-slot>, <subclass-slot>, <virtual-slot>, <init-arg>, <init-spec>,
      <parameter-list>, <param-list>, <value-list>, <fixed-param-list>, <key-param-list>,
         <var-param-list>, <req-param>, <key-param>, <rest-param>, <req-value>,
         <rest-value>,
      <explicit-function-defn>, <explicit-constant-defn>, <explicit-variable-defn>,
         <explicit-macro-defn>, <explicit-body-macro-defn>, <explicit-list-macro-defn>,
         <explicit-stmt-macro-defn>, <explicit-func-macro-defn>,
      <sealed-domain>, <vendor-option>,
      <fragment>, <computed-constant>, <type-fragment>, <code-fragment>, <name-fragment>
      ;

   export
      adjs,
      all-defns,
      all-keys?,
      all-keys?-setter,
      bindings,
      bindings-setter,
      code-fragment,
      definition,
      definition-setter,
      direct-supers,
      explicit-defn,
      explicit-defn-setter,
      exported?,
      exported?-setter,
      expr,
      expr-setter,
      file-markup-tokens,
      file-markup-tokens-setter,
      fragment-names,
      getter,
      getter-setter,
      implicit-defns,
      implicit-defns-setter,
      import-name,
      import-name-setter,
      init-args,
      init-spec,
      init-spec-setter,
      key-params,
      key-params-setter,
      local-name,
      local-name-setter,
      markup-tokens,
      markup-tokens-setter,
      modules,
      modules-setter,
      parameter-list,
      parameter-list-setter,
      req-params,
      req-params-setter,
      req-values,
      req-values-setter,
      rest-param,
      rest-param-setter,
      rest-value,
      rest-value-setter,
      sealed-domains,
      sealed-domains-setter,
      sealed?,
      sealed?-setter,
      sealed-types,
      setter,
      setter-setter,
      slots,
      source-name,
      source-text,
      stray?,
      symbol,
      type,
      type-setter,
      unknown-reexport-sources,
      unknown-reexport-sources-setter,
      used-library,
      used-library-setter,
      used-module,
      used-module-setter,
      value,
      value-setter,
      vendor-options,
      ;
end module;
