#! /bin/sh
# postinst script for Gwydion Dylan
#
# see: dh_installdeb(1)

if [ "$1" = configure ]; then
  if command -v install-docs > /dev/null 2>&1; then
    install-docs -i /usr/share/doc-base/gdapi-doc
    install-docs -i /usr/share/doc-base/gdlibs-doc
    install-docs -i /usr/share/doc-base/gdmaint-doc
    install-docs -i /usr/share/doc-base/gduser-doc
    install-docs -i /usr/share/doc-base/tutorial-doc
  fi
fi

#DEBHELPER#

