library:    doctower
executable: doctower
files:	    tool/library
	    common/module
	    common/common
	    common/locations
	    conditions/module
	    conditions/conditions
	    ordered-tree/module
	    ordered-tree/ordered-tree
	    internal-rep/module
	    internal-rep/body-elements
	    internal-rep/helpers
	    internal-rep/misc-elements
	    internal-rep/printers
	    internal-rep/quote-elements
	    internal-rep/toc-nav-elements
	    internal-rep/topic-elements
	    configs/module
	    configs/configs
	    parser-common/module
	    parser-common/parser-common
	    markup-parser/module
	    markup-parser/markup-parser
	    markup-parser/helpers
	    markup-parser/primitives
	    markup-parser/divisions
	    markup-parser/titles
	    markup-parser/directives
	    markup-parser/content
	    markup-parser/lists
	    markup-parser/paras-frags
	    markup-parser/words
	    markup-translator/module
	    markup-translator/check-helpers
	    markup-translator/topic-processing
	    markup-translator/content-processing
	    markup-translator/markup-processing
	    dylan-parser/module
	    dylan-parser/dylan-parser
	    dylan-parser/helpers
	    dylan-parser/lexical-terminals
	    dylan-parser/recovery
	    dylan-parser/interchange
	    dylan-parser/lines-and-comments
	    dylan-parser/lexical-grammar
	    dylan-parser/phrase-grammar
	    dylan-parser/definitions
	    dylan-parser/printers
	    dylan-translator/module
	    dylan-translator/dylan-translator
	    source-files/module
	    source-files/dylan-file
	    source-files/markup-file
	    source-files/toc-file
	    topic-resolver/module
	    topic-resolver/arranging
	    topic-resolver/merging
	    topic-resolver/resolving
	    tasks/module
	    tasks/create-docs
	    tool/module
	    tool/main
	 